-- chunkname: @./_assets/kr1-desktop/sounds/groups.lua

return {
	BlackburnSounds = {
		files = {
			"halloween_abominationexplosion.ogg",
			"halloween_werewolf_alfawolf.ogg",
			"halloween_werewolf_minormoans.ogg",
			"halloween_werewolf_transformation.ogg",
			"kr_ambience_cb_aquelarre.ogg",
			"kr_ambience_cb_ghosts_1.ogg",
			"kr_sfx_cb_crow.ogg",
			"kr_sfx_cb_giantrats1.ogg",
			"kr_sfx_cb_giantrats2.ogg",
			"kr_sfx_cb_lordblackburn_death.ogg",
			"kr_sfx_cb_lordblackburn_specialstomp.ogg",
			"kr_sfx_cb_lordblackburn_swing.ogg",
			"kr_sfx_cb_nessie.ogg",
			"kr_sfx_cb_witch_fast.ogg",
			"kr_sfx_cb_witch_slow.ogg",
			"kr_sfx_cb_witchdeath.ogg",
		},
	},
	EndlessOrcsSounds = {
		files = {
		  "kr_sfx_endless_flametotem_v3.ogg",
		  "kr_sfx_endless_healingtotem_v3.ogg",
		  "kr_sfx_endless_swiftnesstotem_v3.ogg"
		}
	  },
	HalloweenSounds = {
		files = {
			"halloween_abominationexplosion.ogg",
			"halloween_werewolf_alfawolf.ogg",
			"halloween_werewolf_minormoans.ogg",
			"halloween_werewolf_transformation.ogg",
		},
	},
	HeroArcher = {
		files = {
			"Aleria_special_arrow.ogg",
			"Aleria_sumon.ogg",
			"Aleria_wildcat_hit.ogg",
			"Female-Elven-Archer-01c.ogg",
			"Female-Elven-Archer-03a.ogg",
			"Female-Elven-Archer-04b.ogg",
			"Female-Elven-Archer-Death_a.ogg",
			"Level_up.ogg",
		},
	},
	HeroDenas = {
		files = {
			"KingDenas-01d.ogg",
			"KingDenas-02d.ogg",
			"KingDenas-03g.ogg",
			"KingDenas-05c.ogg",
			"KingDenas_sfx_attack.ogg",
			"KingDenas_sfx_order1.ogg",
			"KingDenas_sfx_order3.ogg",
			"Level_up.ogg",
		},
	},
	HeroFrost = {
		files = {
			"Elora_GroundFreeze.ogg",
			"Elora_IceShard.ogg",
			"Elora_IceShardBreak.ogg",
			"Elora_IceShardSummon.ogg",
			"Frost-Mage-02c.ogg",
			"Frost-Mage-03d.ogg",
			"Frost-Mage-04a.ogg",
			"Frost-Mage-Death_01c.ogg",
			"Level_up.ogg",
		},
	},
	HeroMage = {
		files = {
			"Level_up.ogg",
			"Mage_blue_rain_charge.ogg",
			"Mage_blue_rain_drop.ogg",
			"Mage_shadows.ogg",
			"Young-Mage-01d.ogg",
			"Young-Mage-03c.ogg",
			"Young-Mage-04c.ogg",
			"Young-Mage-Death_c.ogg",
		},
	},
	HeroPaladin = {
		files = {
			"Holy-Paladin-02c.ogg",
			"Holy-Paladin-03b.ogg",
			"Holy-Paladin-04a.ogg",
			"Holy-Paladin-Death_b.ogg",
			"Level_up.ogg",
			"Paladin_deflect.ogg",
			"Paladin_shield_buff.ogg",
		},
	},
	HeroRainOfFire = {
		files = {
			"Cinder_special_area.ogg",
			"Cinder_special_fireball_1_start.ogg",
			"Cinder_special_fireball_2_end.ogg",
			"Elemental-02c.ogg",
			"Elemental-03b.ogg",
			"Elemental-04c.ogg",
			"Elemental-Death_c.ogg",
			"Level_up.ogg",
			"Motumbo_hit.ogg",
		},
	},
	HeroReinforcement = {
		files = {
			"Level_up.ogg",
			"Motumbo_charge_special.ogg",
			"Motumbo_hit.ogg",
			"Motumbo_jump_special.ogg",
			"Reinforcement-02c.ogg",
			"Reinforcement-03c.ogg",
			"Reinforcement-04b.ogg",
			"Reinforcement-Death_c.ogg",
		},
	},
	HeroRifleman = {
		files = {
			"Dwarf-Rifleman-02c.ogg",
			"Dwarf-Rifleman-03c.ogg",
			"Dwarf-Rifleman-04c.ogg",
			"Dwarf-Rifleman-Death_c.ogg",
			"Dwarf_brea_shot2.ogg",
			"Dwarf_brea_shot_hit.ogg",
			"Dwarf_mine.ogg",
			"Level_up.ogg",
		},
	},
	HeroRobot = {
		files = {
			"Hacksaw-02c.ogg",
			"Hacksaw-03a.ogg",
			"Hacksaw-04a.ogg",
			"Hacksaw-Death01c.ogg",
			"Level_up.ogg",
			"inferno_lumberjack_drill.ogg",
			"inferno_lumberjack_shootSaw.ogg",
		},
	},
	HeroSamurai = {
		files = {
			"Level_up.ogg",
			"Oni-01c.ogg",
			"Oni-02c.ogg",
			"Oni-04a.ogg",
			"Oni-Death01a.ogg",
			"inferno_oni_groundSwords.ogg",
			"inferno_oni_instakill.ogg",
		},
	},
	HeroThor = {
		files = {
			"KR_sfx_thor_ataqueelectrico.ogg",
			"KR_sfx_thor_lanzamartillo_op2.ogg",
			"KR_sfx_thor_muerte.ogg",
			"KR_sfx_thor_thunder.ogg",
			"Level_up.ogg",
			"Thor_02a.ogg",
			"Thor_03c.ogg",
			"Thor_04c.ogg",
			"Thor_05c.ogg",
		},
	},
	HeroViking = {
		files = {
			"Level_up.ogg",
			"Viking-01b.ogg",
			"Viking-02c.ogg",
			"Viking-03b.ogg",
			"Viking-Death_01d.ogg",
			"Viking_Call.ogg",
			"Viking_Hit.ogg",
			"Viking_StartAttack.ogg",
			"Viking_Transform.ogg",
		},
	},
	InfernoSounds = {
		files = {
			"inferno_boss_death.ogg",
			"inferno_boss_horns.ogg",
			"inferno_boss_stomp.ogg",
		},
	},
	JtEffects = {
		files = {
			"Sound_EnemyJtAttack.ogg",
			"Sound_EnemyJtDeath.ogg",
			"Sound_EnemyJtEat.ogg",
			"Sound_EnemyJtExplode.ogg",
			"Sound_EnemyJtRest.ogg",
			"Sound_HitIce1.ogg",
			"Sound_HitIce2.ogg",
			"Sound_HitIce3.ogg",
		},
	},
	MushroomSounds = {
		files = {
			"KR_sfx_mushroomboss_gas_op1.ogg",
			"KR_sfx_mushroomboss_muerte.ogg",
			"KR_sfx_mushroomcreep_muerte_edit_vanzen.ogg",
			"KR_sfx_mushroomcreep_nacimiento.ogg",
		},
	},
	VeznanEffects = {
		files = {
			"Sound_DemonPortal_Summon.ogg",
			"Sound_DemonPortal_Telein.ogg",
			"Sound_EnemyVeznan_attack.ogg",
			"Sound_EnemyVeznan_death.ogg",
			"Sound_EnemyVeznan_demonFire.ogg",
			"Sound_EnemyVeznan_toDemon.ogg",
			"Sound_SpellTowerHold_Cast.ogg",
			"Sound_SpellTowerHold_Dissipate.ogg",
			"Sound_SpellTowerHold_Hit.ogg",
			"Sound_SpellTowerHold_Trap.ogg",
		},
	},
	common = {
		keep = true,
		files = {
			"Arcane_Ready.ogg",
			"Arcane_Taunt1.ogg",
			"Arcane_Taunt2.ogg",
			"Archer_Ready.ogg",
			"Archer_Taunt1.ogg",
			"Archer_Taunt2.ogg",
			"Artillery_Ready.ogg",
			"Artillery_Taunt1.ogg",
			"Artillery_Taunt2.ogg",
			"BFG_Ready.ogg",
			"BFG_Taunt1.ogg",
			"BFG_Taunt2.ogg",
			"Barbarian_Move.ogg",
			"Barbarian_Ready.ogg",
			"Barbarian_Taunt1.ogg",
			"Barbarian_Taunt2.ogg",
			"Barrack_Move.ogg",
			"Barrack_Ready.ogg",
			"Barrack_Taunt1.ogg",
			"Barrack_Taunt2.ogg",
			"Dwarf-Rifleman-01a.ogg",
			"Elemental-01c.ogg",
			"Elf_Taun1.ogg",
			"Elf_Taun2.ogg",
			"Female-Elven-Archer-02c.ogg",
			"Frost-Mage-01a.ogg",
			"GUITransitionClose.ogg",
			"GUITransitionOpen.ogg",
			"Hacksaw-01c.ogg",
			"Holy-Paladin-01c.ogg",
			"KingDenas-04e.ogg",
			"Level_up.ogg",
			"Mage_Ready.ogg",
			"Mage_Taunt1.ogg",
			"Mage_Taunt2.ogg",
			"Muskateer_Event1.ogg",
			"Muskateer_Event2.ogg",
			"Muskateer_Ready.ogg",
			"Muskateer_Snipe.ogg",
			"Oni-03c.ogg",
			"Paladin_Move.ogg",
			"Paladin_Ready.ogg",
			"Paladin_Taunt1.ogg",
			"Paladin_Taunt2.ogg",
			"Ranger_Ready.ogg",
			"Ranger_Taunt1.ogg",
			"Ranger_Taunt2.ogg",
			"Reinforcement-01a.ogg",
			"Reinforcements_Event1.ogg",
			"Reinforcements_Event2.ogg",
			"Reinforcements_Event3.ogg",
			"Reinforcements_Event4.ogg",
			"Sorcerer_Ready.ogg",
			"Sorcerer_Taunt1.ogg",
			"Sorcerer_Taunt2.ogg",
			"Sound_AchievementWin.ogg",
			"Sound_ArcaneDesintegrate.ogg",
			"Sound_ArrowHit2.ogg",
			"Sound_ArrowHit3.ogg",
			"Sound_ArrowRelease2.ogg",
			"Sound_ArrowRelease3.ogg",
			"Sound_BattleAxe.ogg",
			"Sound_Bomb1.ogg",
			"Sound_Chieftain.ogg",
			"Sound_Coins.ogg",
			"Sound_CommonAreaHit.ogg",
			"Sound_EnemyBigDead.ogg",
			"Sound_EnemyExplode1.ogg",
			"Sound_EnemyGoblinDead.ogg",
			"Sound_EnemyHealing.ogg",
			"Sound_EnemyOrcDead.ogg",
			"Sound_EnemyPuffDead.ogg",
			"Sound_EnemyRocketeer.ogg",
			"Sound_EnemySkeletonBreak2.ogg",
			"Sound_EnemyTrollDead.ogg",
			"Sound_EngineerShot.ogg",
			"Sound_FireballHit.ogg",
			"Sound_FireballUnleash.ogg",
			"Sound_GUIButtonCommon.ogg",
			"Sound_GUIBuyUpgrade.ogg",
			"Sound_GUIMouseOverTowerIcon.ogg",
			"Sound_GUIOpenTowerMenu.ogg",
			"Sound_HumanDead1.ogg",
			"Sound_HumanDead2.ogg",
			"Sound_HumanDead3.ogg",
			"Sound_HumanDead4.ogg",
			"Sound_JuggernautDeath.ogg",
			"Sound_LooseLife.ogg",
			"Sound_MageShot.ogg",
			"Sound_MapNewFlag.ogg",
			"Sound_MapRoad.ogg",
			"Sound_NextWaveReady.ogg",
			"Sound_NotificationClose.ogg",
			"Sound_NotificationOpen.ogg",
			"Sound_NotificationPaperOver.ogg",
			"Sound_NotificationSecondLevel.ogg",
			"Sound_PaladinHeal.ogg",
			"Sound_Polimorph.ogg",
			"Sound_QuestCompleted.ogg",
			"Sound_QuestFailed.ogg",
			"Sound_RallyPointPlaced.ogg",
			"Sound_RayArcane.ogg",
			"Sound_RockElementalDeath.ogg",
			"Sound_RockElementalRally.ogg",
			"Sound_RocketLaunt.ogg",
			"Sound_Sheep.ogg",
			"Sound_Shootgun.ogg",
			"Sound_Shrapnel.ogg",
			"Sound_Sniper.ogg",
			"Sound_Sorcerer.ogg",
			"Sound_SpellRefresh.ogg",
			"Sound_SpellSelect.ogg",
			"Sound_SpiderAttack1.ogg",			
			"Sound_SpiderAttack2.ogg",	
			"Sound_Teleport.ogg",
			"Sound_Tesla_attack_1.ogg",
			"Sound_Tesla_attack_2.ogg",
			"Sound_Thorn.ogg",
			"Sound_TowerBuilding.ogg",
			"Sound_TowerUpgrade.ogg",
			"Sound_TowerOpenDoor.ogg",
			"Sound_TowerSell.ogg",
			"Sound_TowerSoldierSasquashRally.ogg",
			"Sound_TowerSoldierSasquashReady.ogg",
			"Sound_WaveIncoming.ogg",
			"Sound_WinStars.ogg",
			"Sound_WolfAttack.ogg",
			"Sound_WolfAttack2.ogg",
			"Tesla_Ready.ogg",
			"Tesla_Taunt1.ogg",
			"Tesla_Taunt2a.ogg",
			"Tesla_Taunt2b.ogg",
			"Tesla_Taunt2c.ogg",
			"Thor_01a.ogg",
			"Viking-01b.ogg",
			"Young-Mage-02a.ogg",
			"inapp_atfreezeend.ogg",
			"inapp_atfreezestart.ogg",
			"inapp_cash.ogg",
			"inapp_chin.ogg",
			"inapp_freeze.ogg",
			"inapp_gems.ogg",
			"inapp_gnome.ogg",
			"inapp_hearts.ogg",
			"inapp_nuke.ogg",
			"inapp_nuke_falling.ogg",
---蒸汽部队			
			"Steam_Troop_Attack.ogg",
			"steam_troopers_taunt-1.ogg",
			"steam_troopers_taunt-2.ogg",
			"steam_troopers_taunt-3.ogg",
			"steam_troopers_taunt-4.ogg",
			"steam_troopers_taunt-5.ogg",
			"steam_troopers_taunt-6.ogg",
			"steam_troopers_airstrike.ogg",
---时间法师			
			"time_wizard_taunt_ready.ogg",
			"time_wizard_taunt_guard.ogg",
			"time_wizard_taunt_sandstorm.ogg",			
			"ancient_guardian_spawn.ogg",
			"ancient_guardian_death.ogg",
			"ancient_guardian_taunt1.ogg",
			"ancient_guardian_taunt2.ogg",
			"ancient_guardian_taunt3.ogg",
			"ancient_guardian_taunt4.ogg",
---精英军团弓兵			
			"legionnaire_taunt_1.ogg",
			"legionnaire_taunt_2.ogg",
			"kre_sfx_arivan_fireballsummon[op2].ogg",
---尼古拉			
			"hero_voltaire_taunt-1.ogg",
			"hero_voltaire_taunt-2.ogg",
			"hero_voltaire_taunt-3.ogg",
			"hero_voltaire_taunt-4.ogg",
			"hero_voltaire_taunt-5.ogg",
			"kr4_power_juggernaut_liftoff_transform.ogg",
			"kr4_hero_tank_groundslam_lift.ogg",
---毒蛇			
			"hero_viper_curseattack.ogg",
			"hero_viper_taunt_1.ogg",
			"hero_viper_taunt_2.ogg",
			"hero_viper_taunt_3.ogg",
			"hero_viper_taunt_4.ogg",
			"hero_viper_taunt_5.ogg",
			"80__-3R.wav",
--KRV
			"kr4_generic_combat1.ogg",
			"kr4_generic_combat2.ogg",
			"kr4_generic_combat3.ogg",			
		},
		ids = {},
	},
	rebbborn = {
		files = {
			
		}
	}
}
