-- chunkname: @/var/folders/r9/xbxmw8n51957gv9ggzrytvf80000gp/T/com.ironhidegames.frontiers.windows.steam.ep3S4swo/_assets/kr2-desktop/sounds/groups.lua

return {
	AmazonSounds = {
		files = {
			"amazon_taunt_1.ogg",
			"amazon_taunt_2.ogg",
		},
	},
	BossEfreeti = {
		files = {
			"boss_efreeti_clapping.ogg",
			"boss_efreeti_death.ogg",
			"boss_efreeti_evillaugh.ogg",
			"boss_efreeti_snapping.ogg",
			"boss_efreeti_summon.ogg",
			"efreeti_doors.ogg",
			"efreeti_towers_released.ogg",
		},
	},
	BossMonkey = {
		files = {
			"boss_mono_attack.ogg",
			"boss_mono_chestdrum.ogg",
			"boss_mono_chimps_1.ogg",
			"boss_mono_chimps_2.ogg",
			"boss_mono_chimps_3.ogg",
			"boss_mono_death.ogg",
			"boss_mono_enterscene.ogg",
			"boss_mono_saltototem.ogg",
			"boss_mono_totem.ogg",
		},
	},
	DwarfHeroSounds = {
		files = {
			"dwarfHero_taunt_confirm_1.ogg",
			"dwarfHero_taunt_confirm_2.ogg",
			"dwarfHero_taunt_confirm_3.ogg",
			"dwarfHero_taunt_death.ogg",
		},
	},
	DwarfSounds = {
		files = {
			"dwarfArcher_taunt_1.ogg",
			"dwarfArcher_taunt_2.ogg",
			"dwarfBarracks_taunt_1.ogg",
			"dwarf_taunt_1.ogg",
			"dwarf_taunt_2.ogg",
		},
	},
	ElvesLevelSounds = {
		files = {},
	},
	EndlessDesertSounds = {
		files = {
			"krf_sfx_endless_invisibility_consitar.ogg",
			"krf_sfx_endless_obelisk_v3.ogg",
			"krf_sfx_endless_sandhole.ogg",
		},
	},
	FrontiersAmbienceSounds = {
		files = {},
	},
	FrontiersEndlessToeeBossSounds = {
		files = {
			"krf_toee_aliengoddess_screech[op3].ogg",
			"krf_toee_aliengoddess_spit.ogg",
			"krf_toee_alienqueen_acid[impact].ogg",
			"krf_toee_alienqueen_spawn.ogg",
		},
	},
	FrontiersEndlessToeeMiniBossSounds = {
		files = {
			"krf_toee_reaperlord_attack[op2].ogg",
			"krf_toee_reaperlord_death.ogg",
		},
	},
	FrontiersFinalBoss = {
		files = {
			"Sound_Tesla_attack_1.ogg",
			"Sound_Tesla_attack_2.ogg",
			"boss_umbra_death.ogg",
			"boss_umbra_explode.ogg",
			"boss_umbra_openportal.ogg",
			"boss_umbra_release_1.ogg",
			"boss_umbra_release_2.ogg",
			"boss_umbra_respawn.ogg",
			"boss_umbra_shootray.ogg",
			"boss_umbra_sphere_join.ogg",
			"boss_umbra_sphere_rise.ogg",
			"boss_umbra_teleport.ogg",
			"boss_umbra_tower.ogg",
		},
	},
	FrontiersJungleAmbienceSounds = {
		files = {
			"jungle_1.ogg",
		},
	},
	FrontiersLevelSounds = {
		files = {},
	},
	FrontiersUndergroundAmbienceSounds = {
		files = {
			"ambience_underground_1.ogg",
			"ambience_underground_2.ogg",
		},
	},
	GenericSound = {
		files = {},
	},
	GenieSounds = {
		files = {
			"genie_taunt_1.ogg",
			"genie_taunt_2.ogg",
		},
	},
	HWFrankensteinTower = {
		files = {
			"FrankyTower-01d.ogg",
			"FrankyTower-02f.ogg",
			"FrankyTower-03c.ogg",
			"FrankyTower-04a.ogg",
			"Sound_Tesla_attack_1.ogg",
			"Sound_Tesla_attack_2.ogg",
			"halloween_tesla_charge.ogg",
		},
	},
	HWHeadlessHorseman = {
		files = {
			"HeadlessHorseman-03a_WET.ogg",
			"halloween_headless_sinrisa_conacorde.ogg",
		},
	},
	HWVampireBoss = {
		files = {
			"halloween_vampireboss_death.ogg",
			"halloween_vampireboss_drainlife.ogg",
			"halloween_vampireboss_gates.ogg",
		},
	},
	HWVampiress = {
		files = {
			"Vampiress-01c.ogg",
			"Vampiress-02c.ogg",
			"Vampiress-03c.ogg",
			"Vampiress-Death02c.ogg",
			"halloween_vampiress_areaattack_confilo.ogg",
			"halloween_vampiress_drainlifeOP2.ogg",
		},
	},
	HalloweenSounds = {
		files = {
			"halloween_abominationexplosion.ogg",
			"halloween_werewolf_alfawolf.ogg",
			"halloween_werewolf_minormoans.ogg",
			"halloween_werewolf_transformation.ogg",
		},
	},
	HeroAlien = {
		files = {
			"alien_taunt_confirm_1.ogg",
			"alien_taunt_confirm_2.ogg",
			"alien_taunt_confirm_3.ogg",
			"alien_taunt_death.ogg",
			"hero_alien_abduction.ogg",
			"hero_alien_death_explosion.ogg",
			"hero_alien_disc_bounce.ogg",
			"hero_alien_disc_throw.ogg",
			"hero_alien_drone_call.ogg",
			"hero_alien_drone_leave.ogg",
			"hero_alien_drone_ray_loop.ogg",
		},
	},
	HeroAlric = {
		files = {
			"alric_taunt_confirm_1.ogg",
			"alric_taunt_confirm_3.ogg",
			"alric_taunt_confirm_4.ogg",
			"alric_taunt_death.ogg",
			"hero_alric_flurry.ogg",
			"hero_alric_sandwarrior.ogg",
		},
	},
	HeroBeastMaster = {
		files = {
			"beastmaster_taunt_confirm_1.ogg",
			"beastmaster_taunt_confirm_2.ogg",
			"beastmaster_taunt_confirm_4.ogg",
			"beastmaster_taunt_death.ogg",
			"hero_beastmaster_bird_attack.ogg",
			"hero_beastmaster_jabali_attack2.ogg",
			"hero_beastmaster_rhino_stampede.ogg",
			"hero_beastmaster_summon_boar.ogg",
			"hero_beastmaster_summon_rhino.ogg",
			"hero_cronan_whiplash.ogg",
		},
	},
	HeroCrab = {
		files = {
			"Hero_Karkinos_Burrow_in.ogg",
			"Hero_Karkinos_Burrow_out.ogg",
			"Hero_Karkinos_Cannon.ogg",
			"Hero_Karkinos_Cannon_explosion.ogg",
			"Hero_Karkinos_Pincer.ogg",
			"Hero_Karkinos_Shield.ogg",
			"Karkinos_01b.ogg",
			"Karkinos_02b.ogg",
			"Karkinos_04b.ogg",
			"Karkinos_Death.ogg",
		},
	},
	HeroDracolich = {
		files = {
			"Bonehart-01a_WET.ogg",
			"Bonehart-03b_WET.ogg",
			"Bonehart-04c_WET.ogg",
			"Bonehart-Death01c_WET.ogg",
			"halloween_bonedragon_attack.ogg",
			"halloween_bonedragon_bonerain.ogg",
			"halloween_bonedragon_kamikaze2.ogg",
			"halloween_bonedragon_respawn_simple.ogg",
			"halloween_bonedragon_soulsplague.ogg",
			"halloween_bonedragon_spawn_congrowl.ogg",
		},
	},
	HeroDragon = {
		files = {
			"dragonHero_confirm1.ogg",
			"dragonHero_confirm2.ogg",
			"dragonHero_confirm3.ogg",
			"hero_dragon_birth.ogg",
			"hero_dragon_death.ogg",
			"hero_dragon_fireball_explode.ogg",
			"hero_dragon_flamethrower.ogg",
			"hero_dragon_napalm.ogg",
			"hero_dragon_smoke.ogg",
			"hero_dragon_spit.ogg",
		},
	},
	HeroGiant = {
		files = {
			"giant_taunt_confirm_1.ogg",
			"giant_taunt_confirm_2.ogg",
			"giant_taunt_confirm_3.ogg",
			"giant_taunt_death.ogg",
			"hero_grawl_bigpunch.ogg",
			"hero_grawl_boulder_hit.ogg",
			"hero_grawl_boulder_throw.ogg",
			"hero_grawl_stomp.ogg",
		},
	},
	HeroMinotaur = {
		files = {
			"KRF_sfx_minotauro_ataquefuerte.ogg",
			"KRF_sfx_minotauro_carga.ogg",
			"KRF_sfx_minotauro_grito.ogg",
			"KRF_sfx_minotauro_portal.ogg",
			"KRF_sfx_minotauro_remolino_2tiempo.ogg",
			"Minotaur_01b.ogg",
			"Minotaur_02c.ogg",
			"Minotaur_03c.ogg",
			"Minotaur_05e_death.ogg",
		},
	},
	HeroMirage = {
		files = {
			"assassinHero_taunt_confirm_1.ogg",
			"assassinHero_taunt_confirm_3.ogg",
			"assassinHero_taunt_confirm_4.ogg",
			"hero_mirage_lethalstrike_hit.ogg",
			"hero_mirage_lethalstrike_vanish.ogg",
			"hero_mirage_shadowdance_cast.ogg",
			"hero_mirage_shadowdance_hit.ogg",
			"hero_mirage_shadowdodge.ogg",
			"hero_mirage_shadowdodge_puff.ogg",
		},
	},
	HeroMonk = {
		files = {
			"Hero_Monk_Counter.ogg",
			"Hero_Monk_Firedragon.ogg",
			"Hero_Monk_Hadoken.ogg",
			"Hero_Monk_Multihit_punch.ogg",
			"Hero_Monk_Multihit_scream_1.ogg",
			"Hero_Monk_Multihit_scream_2.ogg",
			"Hero_Monk_Snake_attack.ogg",
			"Monk_01c.ogg",
			"Monk_03c.ogg",
			"Monk_04b.ogg",
			"Monk_Death.ogg",
		},
	},
	HeroMonkeyGod = {
		files = {
			"Level_up.ogg",
			"Saitam-confirm_01b[2].ogg",
			"Saitam-death_01b[2].ogg",
			"Saitam_confirm-03c.ogg",
			"Saitam_confirm-04c.ogg",
			"Saitam_confirm-05c.ogg",
			"krf_toee_saitam_angrygod[flames-loop].ogg",
			"krf_toee_saitam_angrygod[scream].ogg",
			"krf_toee_saitam_attack[op1].ogg",
			"krf_toee_saitam_attack[op2].ogg",
			"krf_toee_saitam_cloudclimb_v2[op2].ogg",
			"krf_toee_saitam_clouddrop.ogg",
			"krf_toee_saitam_cloudtransport.ogg",
			"krf_toee_saitam_monkeypalm[op1].ogg",
			"krf_toee_saitam_polespin[loop-end].ogg",
			"krf_toee_saitam_polespin[loop].ogg",
			"krf_toee_saitam_tetsubostorm[op1].ogg",
		},
	},
	HeroPirate = {
		files = {
			"blackthorne_taunt_confirm_1.ogg",
			"blackthorne_taunt_confirm_2.ogg",
			"blackthorne_taunt_confirm_3.ogg",
			"blackthorne_taunt_confirm_4.ogg",
			"blackthorne_taunt_confirm_5.ogg",
			"blackthorne_taunt_death.ogg",
			"hero_blackthorne_barrel.ogg",
			"hero_blackthorne_kraken.ogg",
		},
	},
	HeroPriest = {
		files = {
			"hero_priest_consecrate.ogg",
			"hero_priest_healing.ogg",
			"hero_priest_teleport.ogg",
			"priest_taunt_confirm_1.ogg",
			"priest_taunt_confirm_2.ogg",
			"priest_taunt_confirm_3.ogg",
			"priest_taunt_confirm_4.ogg",
			"priest_taunt_death.ogg",
		},
	},
	HeroVanHelsing = {
		files = {
			"Dante-02a.ogg",
			"Dante-03a.ogg",
			"Dante-04d.ogg",
			"Dante-Death01c.ogg",
			"halloween_helsing_holywater_conquemadura.ogg",
			"halloween_helsing_relic.ogg",
		},
	},
	HeroVoodooWitch = {
		files = {
			"KRF_sfx_vodoo_ataqueV3.ogg",
			"KRF_sfx_vodoo_calaveraV3_op2.ogg",
			"KRF_sfx_vodoo_kamikazegolpev3.ogg",
			"KRF_sfx_vodoo_kamikazelanza.ogg",
			"KRF_sfx_vodoo_munieco.ogg",
			"Vodoo_02b.ogg",
			"Vodoo_03b.ogg",
			"Vodoo_04b.ogg",
			"Vodoo_05d.ogg",
		},
	},
	HeroWizard = {
		files = {
			"hero_nivus_attack.ogg",
			"hero_nivus_desintegrate.ogg",
			"hero_nivus_magicmissile_hit.ogg",
			"hero_nivus_magicmissile_summon.ogg",
			"hero_nivus_teleport.ogg",
			"wizzard_taunt_confirm_2.ogg",
			"wizzard_taunt_confirm_3.ogg",
			"wizzard_taunt_confirm_4.ogg",
			"wizzard_taunt_death.ogg",
		},
	},
	LegionnaireSounds = {
		files = {
			"legionnaire_taunt_1.ogg",
			"legionnaire_taunt_2.ogg",
		},
	},
	Level1SpecialEnding = {
		files = {
			"Sound_SpellTowerHold_Cast.ogg",
			"Sound_SpellTowerHold_Dissipate.ogg",
			"boss_cinematic.ogg",
		},
	},
	PirateBigSounds = {
		files = {
			"Pirate_Big_01c.ogg",
			"Pirate_Big_02c.ogg",
		},
	},
	PirateBoatSounds = {
		files = {
			"PirateBoat_01c.ogg",
			"PirateBoat_02c.ogg",
			"PirateBoat_03a.ogg",
		},
	},
	PirateTowerSounds = {
		files = {
			"Pirate_Tower_01a.ogg",
			"Pirate_Tower_02b.ogg",
		},
	},
	PiratesSounds = {
		files = {
			"pirate_taunt_1.ogg",
			"pirate_taunt_2.ogg",
			"pirate_taunt_3.ogg",
		},
	},
	RisingTidesSounds = {
		files = {
			"Blacksurge_holdtower.ogg",
			"Bluegale_storm_ambience.ogg",
			"Bluegale_storm_summon.ogg",
			"Explosion_water.ogg",
			"Gunboat_death.ogg",
			"Gunboat_shooting.ogg",
			"Sound_Polimorph.ogg",
			"Waterenemy_death.ogg",
			"Whale_spawn.ogg",
			"boss_death.ogg",
			"boss_leviathan_tentacle_grab.ogg",
			"boss_spawn.ogg",
			"boss_tentacle_spawn.ogg",
			"ship_path_break.ogg",
		},
	},
	SaurianKingBoss = {
		files = {
			"KRF_sfx_saurianboss_martillo_1t.ogg",
			"KRF_sfx_saurianboss_muerte.ogg",
			"KRF_sfx_saurianboss_op1.ogg",
			"KRF_sfx_saurianboss_temblor.ogg",
		},
	},
	SaurianSniperSounds = {
		files = {
			"KRF_sfx_suarian_sniper.ogg",
		},
	},
	SpecialAlienSounds = {
		files = {
			"alien_egg_open.ogg",
		},
	},
	SpecialBanthaSounds = {
		files = {
			"bantha_fart.ogg",
			"bantha_roar.ogg",
		},
	},
	SpecialBlackDragon = {
		files = {
			"dragonHero_confirm1.ogg",
			"dragonHero_confirm2.ogg",
			"dragonHero_confirm3.ogg",
			"dragonHero_confirm4.ogg",
			"hero_dragon_flamethrower.ogg",
		},
	},
	SpecialCarnivorePlantSounds = {
		files = {
			"carnivore_plant.ogg",
		},
	},
	SpecialCutTreeSounds = {
		files = {
			"cut_trees.ogg",
		},
	},
	SpecialFrog = {
		files = {
			"frog_dance.ogg",
		},
	},
	SpecialIndianaSounds = {
		files = {
			"indiana.ogg",
			"indiana_runs.ogg",
			"indiana_select.ogg",
		},
	},
	SpecialMermaid = {
		files = {
			"mermaid.ogg",
		},
	},
	SpecialMountainDoor = {
		files = {
			"mountain_door.ogg",
		},
	},
	SpecialStargate = {
		files = {
			"stargate.ogg",
		},
	},
	SpecialTusken = {
		files = {
			"tusken.ogg",
		},
	},
	SpecialVolcanoSounds = {
		files = {
			"volcano_lavaShot.ogg",
			"volcano_lavaShotHit.ogg",
			"volcano_splash.ogg",
			"volcano_virginScream.ogg",
		},
	},
	SpecialWorm = {
		files = {
			"worm_bite.ogg",
			"worm_dirtLoop.ogg",
		},
	},
	common = {
		keep = true,
		files = {
			"Archer_Ready.ogg",
			"Archer_Taunt1.ogg",
			"Archer_Taunt2.ogg",
			"Artillery_Ready.ogg",
			"Artillery_Taunt1.ogg",
			"Artillery_Taunt2.ogg",
			"Barrack_Move.ogg",
			"Barrack_Ready.ogg",
			"Barrack_Taunt1.ogg",
			"Barrack_Taunt2.ogg",
			"Bonehart-02b_WET.ogg",
			"Dante-01a.ogg",
			"GUITransitionClose.ogg",
			"GUITransitionOpen.ogg",
			"Karkinos_03d.ogg",
			"Level_up.ogg",
			"Mage_Ready.ogg",
			"Mage_Taunt1.ogg",
			"Mage_Taunt2.ogg",
			"Minotaur_04b.ogg",
			"Monk_02b.ogg",
			"Reinforcements_Event1.ogg",
			"Reinforcements_Event2.ogg",
			"Reinforcements_Event3.ogg",
			"Reinforcements_Event4.ogg",
			"Saitam-confirm_02c[2].ogg",
			"Sound_AchievementWin.ogg",
			"Sound_ArrowHit2.ogg",
			"Sound_ArrowHit3.ogg",
			"Sound_ArrowRelease2.ogg",
			"Sound_ArrowRelease3.ogg",
			"Sound_BattleAxe.ogg",
			"Sound_Bomb1.ogg",
			"Sound_Coins.ogg",
			"Sound_CommonAreaHit.ogg",
			"Sound_EnemyBigDead.ogg",
			"Sound_EnemyExplode1.ogg",
			"Sound_EnemyGoblinDead.ogg",
			"Sound_EnemyHealing.ogg",
			"Sound_EnemyOrcDead.ogg",
			"Sound_EnemyPuffDead.ogg",
			"Sound_EnemySkeletonBreak2.ogg",
			"Sound_EnemyTrollDead.ogg",
			"Sound_EngineerShot.ogg",
			"Sound_FireballHit.ogg",
			"Sound_FireballUnleash.ogg",
			"Sound_GUIButtonCommon.ogg",
			"Sound_GUIBuyUpgrade.ogg",
			"Sound_GUIMouseOverTowerIcon.ogg",
			"Sound_GUIOpenTowerMenu.ogg",
			"Sound_HumanDead1.ogg",
			"Sound_HumanDead2.ogg",
			"Sound_HumanDead3.ogg",
			"Sound_HumanDead4.ogg",
			"Sound_LooseLife.ogg",
			"Sound_MageShot.ogg",
			"Sound_MapNewFlag.ogg",
			"Sound_MapRoad.ogg",
			"Sound_NextWaveReady.ogg",
			"Sound_NotificationClose.ogg",
			"Sound_NotificationOpen.ogg",
			"Sound_NotificationPaperOver.ogg",
			"Sound_NotificationSecondLevel.ogg",
			"Sound_QuestCompleted.ogg",
			"Sound_QuestFailed.ogg",
			"Sound_RallyPointPlaced.ogg",
			"Sound_RocketLaunt.ogg",
			"Sound_Shootgun.ogg",
			"Sound_Shrapnel.ogg",
			"Sound_Sniper.ogg",
			"Sound_Sorcerer.ogg",
			"Sound_SpellRefresh.ogg",
			"Sound_SpellSelect.ogg",
			"Sound_SpiderAttack1.ogg",
			"Sound_SpiderAttack2.ogg",
			"Sound_TowerBuilding.ogg",
			"Sound_TowerOpenDoor.ogg",
			"Sound_TowerSell.ogg",
			"Sound_WaveIncoming.ogg",
			"Sound_WinStars.ogg",
			"Sound_WolfAttack.ogg",
			"Sound_WolfAttack2.ogg",
			"Vodoo_01c.ogg",
			"alien_taunt_confirm_4.ogg",
			"alric_taunt_confirm_2.ogg",
			"archmage_attack.ogg",
			"archmage_explosion.ogg",
			"archmage_precharge.ogg",
			"archmage_taunt_explosion.ogg",
			"archmage_taunt_ready.ogg",
			"archmage_taunt_twister.ogg",
			"archmage_twister.ogg",
			"assassinHero_taunt_confirm_2.ogg",
			"assassin_gold.ogg",
			"assassin_sneakattack.ogg",
			"assassin_taunt_counter.ogg",
			"assassin_taunt_gold.ogg",
			"assassin_taunt_ready.ogg",
			"assassin_taunt_sneak.ogg",
			"axlethrower_taunt_ready.ogg",
			"axlethrower_taunt_totem1.ogg",
			"axlethrower_taunt_totem2.ogg",
			"axlethrower_totem_spirits.ogg",
			"axlethrower_totem_vanish.ogg",
			"axlethrower_totem_weakness.ogg",
			"beastmaster_taunt_confirm_3.ogg",
			"blackthorne_taunt_confirm_3.ogg",
			"blazefang_attack.ogg",
			"blazefang_death.ogg",
			"canibal_eating.ogg",
			"canibal_necromancer.ogg",
			"canibal_zombie_one.ogg",
			"canibal_zombie_three.ogg",
			"canibal_zombie_two.ogg",
			"crossbow_eagle.ogg",
			"crossbow_taunt_eagle.ogg",
			"crossbow_taunt_multishot.ogg",
			"crossbow_taunt_ready.ogg",
			"darter_teleout.ogg",
			"dragonHero_confirm4.ogg",
			"dwaarp_attack.ogg",
			"dwaarp_drillIn.ogg",
			"dwaarp_drillOut.ogg",
			"dwaarp_lavaSmash.ogg",
			"earthquake_taunt_drill.ogg",
			"earthquake_taunt_ready.ogg",
			"earthquake_taunt_scorched.ogg",
			"giant_taunt_confirm_4.ogg",
			"inapp_atfreezeend.ogg",
			"inapp_atfreezestart.ogg",
			"inapp_cash.ogg",
			"inapp_chin.ogg",
			"inapp_freeze.ogg",
			"inapp_gems.ogg",
			"inapp_gnome.ogg",
			"inapp_hearts.ogg",
			"inapp_nuke.ogg",
			"inapp_nuke_falling.ogg",
			"mecha_dropoil.ogg",
			"mecha_spawn.ogg",
			"mecha_steamrelease.ogg",
			"mecha_taunt_misc.ogg",
			"mecha_taunt_missile.ogg",
			"mecha_taunt_ready.ogg",
			"mecha_taunt_slow.ogg",
			"mecha_walk.ogg",
			"mecromancer_summon.ogg",
			"myrmidon_bite.ogg",
			"necromancer_attack.ogg",
			"necromancer_deathknight_taunt_1.ogg",
			"necromancer_deathknight_taunt_2.ogg",
			"necromancer_pestilence.ogg",
			"necromancer_taunt_dknight.ogg",
			"necromancer_taunt_pesti.ogg",
			"necromancer_taunt_ready.ogg",
			"nightscale_invisibility.ogg",
			"priest_taunt_confirm_5.ogg",
			"sandwraith_coffin.ogg",
			"saurian_brute_attack.ogg",
			"savant_attack.ogg",
			"savant_open_portal.ogg",
			"savant_portal_loop.ogg",
			"savant_telein.ogg",
			"templar_arterialStrike.ogg",
			"templar_holyGrail.ogg",
			"templar_taunt_1.ogg",
			"templar_taunt_2.ogg",
			"templar_taunt_3.ogg",
			"templar_taunt_ready.ogg",
			"wasp_1.ogg",
			"wasp_2.ogg",
			"wasp_3.ogg",
			"wilhelm_scream.ogg",
			"wizzard_taunt_confirm_1.ogg",
			"worm_bite.ogg",
			"worm_dirtLoop.ogg",
			"krf_toee_aliengoddess_screech[op3].ogg",
		},
		ids = {},
	},
}
