-- chunkname: @./kr3-desktop/assets/sounds/groups.lua

return {
	ElvenWoodsAmbienceSounds = {
		files = {
			"kre_sfx_ambience_singlebirdandstream.ogg",
		},
	},
	ElvesBajNimenBossSounds = {
		files = {
			"kro_sfx_bitteringrancor_boss-death[conriser].ogg",
			"kro_sfx_bitteringrancor_boss-heal.ogg",
			"kro_sfx_bitteringrancor_boss-rangedattack[op2].ogg",
			"kro_sfx_bitteringrancor_boss-shadowstorm[cast].ogg",
			"kro_sfx_bitteringrancor_boss-shadowstorm[impact].ogg",
			"kro_sfx_bitteringrancor_boss-shadowstorm[travel].ogg",
			"kro_sfx_bitteringrancor_boss-tailwhip.ogg",
		},
	},
	ElvesBossBramSounds = {
		files = {
			"kro_sfx_bram_death[conexplo].ogg",
			"kro_sfx_bram_fistcharge.ogg",
			"kro_sfx_bram_groundstomp.ogg",
			"kro_sfx_bram_sopapo[conwhoosh].ogg",
		},
	},
	ElvesCommonSounds = {
		files = {
			"Viking_Transform.ogg",
			"kr3_sfx_arcanearcher_sleepingarrow-op1.ogg",
			"kr3_sfx_archanearcher_arcaneexplotion_v3.ogg",
			"kr3_sfx_basicbarracks_fight.ogg",
			"kr3_sfx_basicwizard_doublebolt-op1.ogg",
			"kr3_sfx_bladesinger_bladedance_v2-op2.ogg",
			"kr3_sfx_bladesinger_perfectparry_v2-op2-faded.ogg",
			"kr3_sfx_druidhenge_bearattack_v4-op1.ogg",
			"kr3_sfx_druidhenge_beardeath_v3_op1-condesplome.ogg",
			"kr3_sfx_druidhenge_bearsummon_v3-op2.ogg",
			"kr3_sfx_druidhenge_bouldersummon.ogg",
			"kr3_sfx_druidhenge_rockthrow_v2-op2-medio.ogg",
			"kr3_sfx_druidhenge_sylvancursecast_v4-op2.ogg",
			"kr3_sfx_elvenhighmage_sentinelactivate.ogg",
			"kr3_sfx_elvenhighmage_sentinelshot_v2-op1.ogg",
			"kr3_sfx_forestkeeper_ancientoakspear_LOW_v1+3db.ogg",
			"kr3_sfx_forestkeeper_circleofhealing-CONGAITA_HI.ogg",
			"kr3_sfx_forestkeeper_eeriegarden_SINPOPS.ogg",
			"kr3_sfx_forestkeeper_normalspear_v2-op1.ogg",
			"kr3_sfx_goldenbow_arrowshot.ogg",
			"kr3_sfx_goldenbow_flarehit_v2.5.ogg",
			"kr3_sfx_goldenbow_flareshot_v2-convoz.ogg",
			"kr3_sfx_goldenbow_instakill_v2_conchime.ogg",
			"kr3_sfx_goldenbow_instakillarrowshot_v2.ogg",
			"kr3_sfx_highmage_preload_and_travel.ogg",
			"kr3_sfx_highmage_shot.ogg",
			"kr3_sfx_highmage_timecast.ogg",
			"kr3_sfx_highmage_timecastend.ogg",
			"kr3_sfx_lightning_op1.ogg",
			"kr3_sfx_lightning_op2.ogg",
			"kr3_sfx_lightning_op3.ogg",
			"kr3_sfx_stonedruid_boulderexplosion.ogg",
			"kr3_sfx_stonedruid_bouldersummon.ogg",
			"kr3_sfx_stonedruid_boulderthrow-op2.ogg",
			"kr3_sfx_tree_clobber_v2.ogg",
			"kr3_sfx_tree_cocoexplosion[explofuerte].ogg",
			"kr3_sfx_tree_cocothrow.ogg",
			"kr3_sfx_tree_fierynutexplotion.ogg",
			"kr3_sfx_tree_fierynutthrow.ogg",
			"kr3_sfx_tree_leaves.ogg",
			"kr3_sfx_wildmagus_boltcast_v2-op1.ogg",
			"kr3_sfx_wildmagus_disruptioncast_v2.ogg",
			"kr3_sfx_wildmagus_doomcast_v2.ogg",
			"kr3_sfx_wildmagus_doomexplotion_v3-op1.ogg",
			"kr3_sfx_wildmagus_doomloop_v2-op1.ogg",
		},
	},
	ElvesCreepArachnomancerSpiderSpawn = {
		files = {
			"kro_sfx_arachnomancer_spiderspawn[op1].ogg",
		},
	},
	ElvesCreepAvenger = {
		files = {
			"kro_sfx_avenger_lastservice_v2[op2].ogg",
		},
	},
	ElvesCreepEvoker = {
		files = {
			"kro_sfx_evoker_heal[sinshaker].ogg",
		},
	},
	ElvesCreepGolem = {
		files = {
			"kro_sfx_elemental_areaattack.ogg",
			"kro_sfx_elemental_death.ogg",
		},
	},
	ElvesCreepHoplite = {
		files = {
			"kro_sfx_hoplite_summon_v3[singrowl].ogg",
		},
	},
	ElvesCreepHyena = {
		files = {
			"kre_sfx_hyena_ambience_v4[op1_heavysnors].ogg",
			"kre_sfx_hyena_ambience_v4[op2_consnors].ogg",
		},
	},
	ElvesCreepMountedAvenger = {
		files = {
			"kro_sfx_bitteringrancor_mountedavanger-death[conexplo].ogg",
		},
	},
	ElvesCreepRazorboar = {
		files = {
			"kro_sfx_razorboar_charge[sinpisadas].ogg",
		},
	},
	ElvesCreepScreecher = {
		files = {
			"kro_sfx_bitteringrancor_screecher-death.ogg",
			"kro_sfx_bitteringrancor_screecher-scream[op5].ogg",
		},
	},
	ElvesCreepServant = {
		files = {
			"kro_sfx_bitteringrancor_servant-death[op2].ogg",
		},
	},
	ElvesCreepSonOfMactans = {
		files = {
			"kro_sfx_sonofmactans[sinlanding].ogg",
		},
	},
	ElvesCrystalPlant = {
		files = {
			"kro_sfx_crystalbuff.ogg",
			"kro_sfx_crystalice.ogg",
			"kro_sfx_crystalray[op1].ogg",
		},
	},
	ElvesDrizzt = {
		files = {},
	},
	ElvesFinalBoss = {
		files = {
			"kr3_sfx_mactans_touch.ogg",
			"kro_sfx_finalboss_jump.ogg",
			"kro_sfx_gemcrystalbreak[solo]_v1.ogg",
			"kro_sfx_mactans_gemattack[op1].ogg",
			"kro_sfx_mactans_webground[conhissing].ogg",
			"kro_sfx_mactans_webspin[towers].ogg",
			"kro_sfx_malicia_gemattack_v1B.ogg",
			"kro_sfx_malicia_spiderin.ogg",
			"kro_sfx_malicia_spiderout.ogg",
			"kro_sfx_spidergoddess_castspell.ogg",
			"kro_sfx_spidergoddess_castspellwithlaughter.ogg",
			"kro_sfx_spidergoddess_death_v2[larga].ogg",
			"kro_sfx_spidergoddess_fall_v2.ogg",
			"kro_sfx_spidergoddess_killray[conprecarga].ogg",
			"kro_sfx_spidergoddess_morph_v1.ogg",
			"kro_sfx_spidergoddess_superray_v3[descarga].ogg",
			"kro_sfx_spidergoddess_superray_v4[carga].ogg",
		},
	},
	ElvesForgottenTreasureAmbienceSounds = {
		files = {
			"kro_sfx_bubblinglava-AMB.ogg",
			"kro_sfx_dripping[conbichos]-AMB.ogg",
			"kro_sfx_wingflaps-AMB.ogg",
		},
	},
	ElvesForgottenTreasureBalrogSounds = {
		files = {
			"kro_sfx_godieth_attack.ogg",
			"kro_sfx_godieth_bloodpool.ogg",
			"kro_sfx_godieth_death[op2].ogg",
			"kro_sfx_godieth_spit.ogg",
		},
	},
	ElvesForgottenTreasureDarkSpitterSounds = {
		files = {
			"krf_sfx_darkspitter_spit.ogg",
			"kro_sfx_darkspitter_death[op2-sincaida].ogg",
		},
	},
	ElvesForgottenTreasureGrimDevourerSounds = {
		files = {
			"kro_sfx_grimdevourer_consume.ogg",
			"kro_sfx_grimdevourer_death.ogg",
		},
	},
	ElvesForgottenTreasureShadowChampionSounds = {
		files = {
			"kro_sfx_shadowchampion_attack[confuego].ogg",
			"kro_sfx_shadowchampion_death.ogg",
		},
	},
	ElvesForgottenTreasureShadowSpawnSounds = {
		files = {
			"kro_sfx_shadowspawn_death[op1].ogg",
			"kro_sfx_shadowspawn_spawn[op2].ogg",
		},
	},
	ElvesGnome = {
		files = {
			"kro_sfx_gnome_desintegrate_v2[comic].ogg",
			"kro_sfx_gnome_poison_v2[confrasco].ogg",
			"kro_sfx_gnome_polymorf[conchimes].ogg",
			"kro_sfx_gnome_polymorf[conchimes].ogg",
			"kro_sfx_veznan_teleport_v1.ogg",
		},
	},
	ElvesGryphon = {
		files = {
			"kre_sfx_gryphon_land_v3[op1].ogg",
			"kre_sfx_gryphon_shot_v2[end].ogg",
			"kre_sfx_gryphon_shot_v2[end].ogg",
			"kre_sfx_gryphon_shot_v2[op3].ogg",
			"kre_sfx_gryphon_takeoff_v2.ogg",
		},
	},
	ElvesHeroAlleria = {
		files = {
			"Female-Elven-Archer-01c.ogg",
			"Female-Elven-Archer-02c.ogg",
			"Female-Elven-Archer-03a.ogg",
			"Female-Elven-Archer-04b.ogg",
			"Female-Elven-Archer-Death_a.ogg",
			"Level_up.ogg",
		},
	},
	ElvesHeroArivan = {
		files = {
			"Arivan_Confirm-01b.ogg",
			"Arivan_Confirm-02c.ogg",
			"Arivan_Confirm-03a.ogg",
			"Arivan_Death-01a.ogg",
			"Level_up.ogg",
			"kre_sfx_arivan_elementalstorm_v2_op3.ogg",
			"kre_sfx_arivan_fireballhit_v3.ogg",
			"kre_sfx_arivan_fireballshot_v2.ogg",
			"kre_sfx_arivan_fireballsummon[op2].ogg",
			"kre_sfx_arivan_icebolt[hit].ogg",
			"kre_sfx_arivan_iceboltshot_v2[contono].ogg",
			"kre_sfx_arivan_lightningbolt_v2.ogg",
			"kre_sfx_arivan_stonesummon_v2.ogg",
		},
	},
	ElvesHeroBabyMalik = {
		files = {
			"Motumbo_charge_special.ogg",
			"Motumbo_hit.ogg",
			"Motumbo_jump_special.ogg",
			"Reinforcement-01a.ogg",
			"Reinforcement-02c.ogg",
			"Reinforcement-03c.ogg",
			"Reinforcement-04b.ogg",
			"Reinforcement-Death_c.ogg",
		},
	},
	ElvesHeroBolverk = {
		files = {
			"VarlBerserker_confirm-01a.ogg",
			"VarlBerserker_confirm-02a.ogg",
			"VarlBerserker_confirm-03c.ogg",
			"VarlBerserker_confirm-04a.ogg",
			"VarlBerserker_death-01c.ogg",
			"kro_sfx_bolverk_bearcry[op1].ogg",
			"kro_sfx_bolverk_doubleslash[gore].ogg",
		},
	},
	ElvesHeroBruce = {
		files = {
			"Bruce_confirm[2]-01b.ogg",
			"Bruce_confirm[2]-02c.ogg",
			"Bruce_confirm_03d.ogg",
			"Bruce_death[2]-01g.ogg",
			"Level_up.ogg",
			"kro_sfx_bruce_griveousbites.ogg",
			"kro_sfx_bruce_guardianlions-hit[loop-end].ogg",
			"kro_sfx_bruce_guardianlions-hit[loop-start].ogg",
			"kro_sfx_bruce_guardianlions[loop-v2-op1].ogg",
			"kro_sfx_bruce_guardianlions[spell+roar].ogg",
			"kro_sfx_bruce_kingsroar[op1-conimpacto].ogg",
		},
	},
	ElvesHeroCatha = {
		files = {
			"Catha_Confirm-01c.ogg",
			"Catha_Confirm-03c.ogg",
			"Catha_Confirm-04d.ogg",
			"Catha_Death-01c.ogg",
			"Level_up.ogg",
			"kre_sfx_catha_fairydust.ogg",
			"kre_sfx_catha_fairyfury[hit]_v2.ogg",
			"kre_sfx_catha_fairyfury[summon].ogg",
			"kre_sfx_catha_fairysoul_v1.ogg",
			"kre_sfx_catha_fairytale[death].ogg",
			"kre_sfx_catha_fairytale[summon].ogg",
		},
	},
	ElvesHeroDenas = {
		files = {
			"Eridan_Death-01a.ogg",
			"Kingsguard_01d.ogg",
			"Kingsguard_02c.ogg",
			"Level_up.ogg",
			"PrinceDenas-confirm_01a.ogg",
			"PrinceDenas-confirm_02c.ogg",
			"PrinceDenas-confirm_03b.ogg",
			"PrinceDenas-death_01a.ogg",
			"kro_sfx_princedenas_celebrity_v1[severalshots].ogg",
			"kro_sfx_princedenas_mighty_v3[convoz_op3].ogg",
			"kro_sfx_princedenas_sybarite_v1[op1].ogg",
			"kro_sfx_princedenas_wealthy_v1[op2].ogg",
		},
	},
	ElvesHeroDurax = {
		files = {
			"Durax_01a[wet].ogg",
			"Durax_02a[wet].ogg",
			"Durax_03a[wet].ogg",
			"Level_up.ogg",
			"kro_sfx_durax_armblade.ogg",
			"kro_sfx_durax_crystallites.ogg",
			"kro_sfx_durax_death[op1].ogg",
			"kro_sfx_durax_lethalprism_shot_v2.ogg",
			"kro_sfx_durax_movement[loop_end].ogg",
			"kro_sfx_durax_movement[loop_op1].ogg",
			"kro_sfx_durax_movement[loop_op1].ogg",
			"kro_sfx_durax_shardspear[impact].ogg",
			"kro_sfx_durax_shardspear[throw].ogg",
			"kro_sfx_durax_ultimate.ogg",
		},
	},
	ElvesHeroEldritch = {
		files = {
			"Eridan_Death-01a.ogg",
			"Level_up.ogg",
			"Reg'son-confirm_01a.ogg",
			"Reg'son-confirm_02c.ogg",
			"Reg'son-confirm_03d.ogg",
			"Reg'son-death_01c.ogg",
			"kro_sfx_regson_bladescast_v3[conenergia].ogg",
			"kro_sfx_regson_bladescast_v3[sinenergia].ogg",
			"kro_sfx_regson_slash_v1.ogg",
			"kro_sfx_regson_vindicator_v3.ogg",
		},
	},
	ElvesHeroEridan = {
		files = {
			"Eridan_Confirm-01d.ogg",
			"Eridan_Confirm03-01a.ogg",
			"Eridan_Death-01a.ogg",
			"Eridan_confirmextra-01a.ogg",
			"Level_up.ogg",
			"kre_sfx_eridan_doublestrike_v2[mid].ogg",
			"kre_sfx_eridan_nimblefencing.ogg",
		},
	},
	ElvesHeroFaustus = {
		files = {
			"Faustus-confirm_02b2.ogg",
			"Faustus-confirm_03a2.ogg",
			"Faustus-confirm_04b2.ogg",
			"Faustus-death_01e2.ogg",
			"Level_up.ogg",
			"kro_sfx_faustus_activate[op2].ogg",
			"kro_sfx_faustus_enervation_v2_[op1].ogg",
			"kro_sfx_faustus_fireloop_v1.ogg",
			"kro_sfx_faustus_liquidfire_v2_sinchimes.ogg",
			"kro_sfx_faustus_normalattack_v1.ogg",
			"kro_sfx_faustus_teleport_v1[sinarpa].ogg",
			"kro_sfx_veznan_faustus_killray_v3.ogg",
		},
	},
	ElvesHeroForestElemental = {
		files = {
			"Bravebark-confirm_01c.ogg",
			"Bravebark-confirm_02b.ogg",
			"Bravebark-confirm_03d.ogg",
			"Bravebark-death_01a.ogg",
			"Level_up.ogg",
			"kre_sfx_hyena_specialstomp.ogg",
			"kro_sfx_bravebark_branchball_v1[op1].ogg",
			"kro_sfx_bravebark_healing_v1.ogg",
			"kro_sfx_bravebark_oakseeds_v1.ogg",
			"kro_sfx_bravebark_rootspikes_v1.ogg",
			"kro_sfx_bravebark_teleport-in_v1.ogg",
			"kro_sfx_bravebark_teleport-out_v1.ogg",
			"kro_sfx_bravebark_v2[spikesbajos].ogg",
		},
	},
	ElvesHeroGyro = {
		files = {
			"Gyro_confirm-02c.ogg",
			"Gyro_confirm-03c.ogg",
			"Gyro_confirm-04b.ogg",
			"Gyro_death-01d.ogg",
			"Level_up.ogg",
			"kro_sfx_wilbur_attack[concasquillos].ogg",
			"kro_sfx_wilbur_bombsmarch[op1].ogg",
			"kro_sfx_wilbur_boombox.ogg",
			"kro_sfx_wilbur_boombox_box.ogg",
			"kro_sfx_wilbur_calldrones.ogg",
			"kro_sfx_wilbur_dronesattack[metralla]_cut.ogg",
			"kro_sfx_wilbur_smokespit.ogg",
		},
	},
	ElvesHeroLilith = {
		files = {
			"Level_up.ogg",
			"Lilith_confirm-02d[wet].ogg",
			"Lilith_confirm-03f[wet].ogg",
			"Lilith_confirm-04a[wet].ogg",
			"Lilith_death-01a[wet].ogg",
			"kro_sfx_lilith_infernalwheel.ogg",
			"kro_sfx_lilith_reaperharvest.ogg",
			"kro_sfx_lilith_resurrection[op2-conchime].ogg",
			"kro_sfx_lilith_soulreaper[op1].ogg",
			"kro_sfx_lilith_ultimate[darkangels-cast].ogg",
			"kro_sfx_lilith_ultimate[darkangels-hit].ogg",
			"kro_sfx_lilith_ultimate[meteors-impact-op1_singlehit].ogg",
			"kro_sfx_veznan_range_shoot_v1.ogg",
		},
	},
	ElvesHeroLynn = {
		files = {
			"Level_up.ogg",
			"Lynn_confirm_02c.ogg",
			"Lynn_confirm_03a.ogg",
			"Lynn_confirm_04d.ogg",
			"Lynn_death_01b.ogg",
			"kro_sfx_bitteringrancor_lynn-curseofdispair[conprecarga].ogg",
			"kro_sfx_bitteringrancor_lynn-fatesealed.ogg",
			"kro_sfx_bitteringrancor_lynn-hexfury[op3].ogg",
			"kro_sfx_bitteringrancor_lynn-weakeningcurse[sincrackle].ogg",
		},
	},
	ElvesHeroPhoenix = {
		files = {
			"Level_up.ogg",
			"Phoenix2-death_01a.ogg",
			"Phoenix2-death_01a.ogg",
			"kro_sfx_phoenix_basicattack.ogg",
			"kro_sfx_phoenix_blazingoffspring_hit_v2.ogg",
			"kro_sfx_phoenix_blazingoffspring_shot[op1].ogg",
			"kro_sfx_phoenix_eggexplosion.ogg",
			"kro_sfx_phoenix_fireegg_activate_v2.ogg",
			"kro_sfx_phoenix_fireegg_v3.ogg",
			"kro_sfx_phoenix_immolation_v2.ogg",
			"kro_sfx_phoenix_ringoffire_explode_v2.ogg",
			"kro_sfx_phoenix_ringoffire_spawn[op2].ogg",
		},
	},
	ElvesHeroRag = {
		files = {
			"Level_up.ogg",
			"RazzAndRags-death_01a.ogg",
			"RazzAndRags_01b.ogg",
			"RazzAndRags_03d.ogg",
			"RazzAndRags_04c.ogg",
			"kro_sfx_angrygnome_objectspawn[op2].ogg",
			"kro_sfx_gnome_kamihare[sinpops].ogg",
			"kro_sfx_gnome_shot[op1_conchime].ogg",
			"kro_sfx_hammertime[op1_12bits].ogg",
			"kro_sfx_hammertime[op2].ogg",
			"kro_sfx_raggified_attack.ogg",
			"kro_sfx_raggified_groundstomp[medium].ogg",
			"kro_sfx_raggified_transform[op2].ogg",
		},
	},
	ElvesHeroVeznan = {
		files = {
			"Level_up.ogg",
			"Veznan-confirm_01e.ogg",
			"Veznan-confirm_02f.ogg",
			"Veznan-confirm_04_custom_ec.ogg",
			"Veznan_death-[new]01b.ogg",
			"kro_sfx_veznan_arcanenova_v1.ogg",
			"kro_sfx_veznan_darkpact_v1.ogg",
			"kro_sfx_veznan_demondeath_v3.ogg",
			"kro_sfx_veznan_demonfireball_hit_v3.1.ogg",
			"kro_sfx_veznan_demonfireball_throw_v3.ogg",
			"kro_sfx_veznan_magicshackles_v1[op2]-01.ogg",
			"kro_sfx_veznan_range_shoot_v1.ogg",
			"kro_sfx_veznan_soulburn_v8[sinimpacto].ogg",
			"kro_sfx_veznan_teleport_v1.ogg",
		},
	},
	ElvesHeroXin = {
		files = {
			"Level_up.ogg",
			"Xin-confirm_01c.ogg",
			"Xin-confirm_03a.ogg",
			"Xin-confirm_04c.ogg",
			"Xin-death_01a.ogg",
			"kro_sfx_xin_daringstrikehit_v1.ogg",
			"kro_sfx_xin_inspire_v3[op1].ogg",
			"kro_sfx_xin_mindoverbody.ogg",
			"kro_sfx_xin_pandamonium-hit1_v1.ogg",
			"kro_sfx_xin_pandamonium-hit2_v1.ogg",
			"kro_sfx_xin_pandamonium_[op1].ogg",
			"kro_sfx_xin_pandastyle_v3[op2].ogg",
			"kro_sfx_xin_polehit1_v3[conhoo].ogg",
			"kro_sfx_xin_polehit2_v3[conhoo].ogg",
			"kro_sfx_xin_tele-in_v3[op1].ogg",
			"kro_sfx_xin_tele-out_v3.ogg",
		},
	},
	ElvesHyena = {
		files = {
			"kre_sfx_hyena_death.ogg",
			"kre_sfx_hyena_howl[op1_singrowl].ogg",
			"kre_sfx_hyena_specialstomp.ogg",
			"kre_sfx_hyena_wagonexplosion.ogg",
			"kre_sfx_hyena_wagonloop[concadenas].ogg",
			"kre_sfx_hyena_wagonloop[ending].ogg",
		},
	},
	ElvesLevelEightSounds = {
		files = {
			"kro_sfx_bean.ogg",
			"kro_sfx_bean_loop.ogg",
			"kro_sfx_hanselandgretel_escape[arpayrisas].ogg",
			"kro_sfx_peekaboo_v2[op2].ogg",
			"kro_sfx_witch_outsidecurse[op2].ogg",
			"kro_sfx_witch_touch[op1].ogg",
			"kro_sfx_witchdeath_v1[op2].ogg",
		},
	},
	ElvesLevelFifteenSounds = {
		files = {
			"Drow_01c.ogg",
			"Drow_02c.ogg",
			"Drow_03b.ogg",
			"kro_sfx_ambience_spiders_v2[op1].ogg",
		},
	},
	ElvesLevelFiveSounds = {
		files = {
			"kre_sfx_achievement_scissorfingers_v2.ogg",
		},
	},
	ElvesLevelFourSounds = {
		files = {
			"kr3_sfx_tree_path_explosion.ogg",
			"kro_sfx_georgefall_v1.ogg",
		},
	},
	ElvesLevelFourteen = {
		files = {
			"kr3_sfx_mactans_touch.ogg",
			"kro_sfx_ambience_spiders_v2[op1].ogg",
			"kro_sfx_spidereggs[huevo+aranias].ogg",
		},
	},
	ElvesLevelHRSounds = {
		files = {
			"kr3_sfx_tree_path_explosion.ogg",
			"kro_sfx_crystallizedgnoll_v2.ogg",
			"kro_sfx_crystalskull_touch[conrisa].ogg",
			"kro_sfx_gnoll_outofbush_modif.ogg",
			"kro_sfx_hulkingrage_mining_v2[op1].ogg",
			"kro_sfx_hulkingrage_mining_v2[op2].ogg",
			"kro_sfx_unstablecrystal_crystallize[op1].ogg",
		},
	},
	ElvesLevelNineSounds = {
		files = {
			"kro_sfx_crystalserpent_crystalshatter.ogg",
			"kro_sfx_crystalserpent_emerge.ogg",
			"kro_sfx_crystalserpent_passby[sinsublows]_B.ogg",
			"kro_sfx_crystalserpent_scream[op4_pocodelay].ogg",
			"kro_sfx_crystalserpent_serpentsattack.ogg",
			"kro_sfx_crystalserpent_submerge_B.ogg",
			"kro_sfx_faerydragon_attack[solocristalizacion].ogg",
			"kro_sfx_faerydragon_buydragon[op1].ogg",
			"kro_sfx_faerydragon_extraability[solochimes].ogg",
			"kro_sfx_faerydragon_sfx_attack[op2][soloattack]_B.ogg",
		},
	},
	ElvesLevelSevenSounds = {
		files = {
			"kro_sfx_obelix_feed[comic].ogg",
		},
	},
	ElvesLevelTenSounds = {
		files = {
			"kro_sfx_gnome_death[op1].ogg",
			"kro_sfx_gnome_death[op4].ogg",
			"kro_sfx_gnome_death[op7].ogg",
			"kro_sfx_simon_activate_v2.ogg",
			"kro_sfx_simon_blue_v2.ogg",
			"kro_sfx_simon_green_v2.ogg",
			"kro_sfx_simon_red_v2.ogg",
			"kro_sfx_simon_wrong_v2.ogg",
			"kro_sfx_simon_yellow_v2.ogg",
		},
	},
	ElvesLevelThirteen = {
		files = {
			"hero_dragon_death.ogg",
			"hero_dragon_fireball_explode.ogg",
			"hero_dragon_flamethrower.ogg",
			"hero_dragon_smoke.ogg",
			"hero_dragon_spit.ogg",
			"kro_sfx_ashbite_confirm_v1[op1].ogg",
			"kro_sfx_ashbite_confirm_v1[op2].ogg",
			"kro_sfx_barezad_firebreath_v2[end].ogg",
			"kro_sfx_barezad_firebreath_v2[loop].ogg",
			"kro_sfx_barezad_firebreath_v2[starter].ogg",
			"kro_sfx_barezad_fly[loop-op2].ogg",
			"kro_sfx_sorcapprentice_book[op1].ogg",
			"kro_sfx_sorcapprentice_broom.ogg",
			"kro_sfx_sorcapprentice_hat[sinexplo].ogg",
		},
	},
	ElvesLevelThreeSounds = {
		files = {
			"kr_yellow_submarine_custom.ogg",
			"kre_sfx_achievement_mario.ogg",
			"kre_sfx_waterfall_strong.ogg",
			"kro_sfx_dwarfdeath[barrel].ogg",
			"kro_sfx_wilson[op1].ogg",
		},
	},
	ElvesMalicia = {
		files = {
			"kro_sfx_mactans_webspin[towers].ogg",
			"kro_sfx_malicia_comet-end_v3.ogg",
			"kro_sfx_malicia_comet-start_v3[sinfuego].ogg",
			"kro_sfx_malicia_death.ogg",
			"kro_sfx_malicia_shieldbreak[op1].ogg",
			"kro_sfx_malicia_spellcast_[op2].ogg",
			"kro_sfx_malicia_spellcast_[op2]_nolaugh.ogg",
			"kro_sfx_malicia_spiderin.ogg",
			"kro_sfx_malicia_spiderout.ogg",
			"kro_sfx_maliciazealot_summon[wololo_op1].ogg",
		},
	},
	ElvesMalikSpecialSounds = {
		files = {
			"kro_sfx_malik_hammer[concaida].ogg",
		},
	},
	ElvesPlants = {
		files = {
			"kre_sfx_plant_magicmissile.ogg",
			"kre_sfx_plant_ready_conchime.ogg",
		},
	},
	ElvesRoadRunnerSpecialSounds = {
		files = {
			"kro_sfx_roadrunner_meepmeep_modif.ogg",
		},
	},
	ElvesScourger = {
		files = {
			"kre_sfx_scourger_death.ogg",
		},
	},
	ElvesSpecialEwoks = {
		files = {
			"Awok_01b.ogg",
			"Awok_02c.ogg",
		},
	},
	ElvesSpecialGnome = {
		files = {
			"Gnome_01d.ogg",
			"Gnome_02a.ogg",
		},
	},
	ElvesTowerBastionSounds = {
		files = {
			"kro_sfx_bastion_shot[op1]_modif.ogg",
		},
	},
	ElvesTowerTaunts = {
		files = {
			"ArcaneArcher_BurstArrow-01a.ogg",
			"ArcaneArcher_Ready-01a.ogg",
			"ArcaneArcher_SleepArrow-01c.ogg",
			"Archers_Taunt-01a.ogg",
			"Archers_Taunt-02a.ogg",
			"Archers_Taunt-03e.ogg",
			"Barrack_Taunt[2]-01c.ogg",
			"Barrack_Taunt[2]-02c.ogg",
			"Barrack_Taunt[2]-03c.ogg",
			"Barrack_Taunt[2]-04e.ogg",
			"Bladesinger_BladeDance[2]-01a.ogg",
			"Bladesinger_PerfectParry[2]-01d.ogg",
			"Bladesinger_Ready[2]-01b.ogg",
			"Bladesinger_SwirlingEdge[2]-01a.ogg",
			"DruidHenge_Ready-01a.ogg",
			"DruidHenge_Sylvan[2]-01b.ogg",
			"ForestProtector_Ancient[2]-01c.ogg",
			"ForestProtector_Circle[2]-01g.ogg",
			"ForestProtector_Eerie[2]-01a.ogg",
			"ForestProtector_Ready[2]-01c.ogg",
			"GoldenBows_Crimson-01b.ogg",
			"GoldenBows_Mark-01b.ogg",
			"GoldenBows_Ready[2]-01d.ogg",
			"HighMage_ArcaneSentinel-01c.ogg",
			"HighMage_Ready-01a.ogg",
			"HighMage_Timelapse-01c.ogg",
			"Mage_Taunt-01e.ogg",
			"Mage_Taunt-03d.ogg",
			"Mage_Taunt[2]-02a.ogg",
			"PapaTree_Clobberin[2]-01e.ogg",
			"PapaTree_Fiery[2]-01d.ogg",
			"PapaTree_Ready[2]-01d.ogg",
			"StoneDruid_Taunt-01b.ogg",
			"StoneDruid_Taunt-02b.ogg",
			"StoneDruid_Taunt-03a.ogg",
			"WildMagus_Doom[2]-01b.ogg",
			"WildMagus_Ready-01a.ogg",
			"WildMagus_Silence-01c.ogg",
		},
	},
	ElvesUnstableCrystalSounds = {
		files = {
			"kro_sfx_unstablecrystal_healing_modif.ogg",
			"kro_sfx_unstablecrystal_ready[op4]_modif.ogg",
		},
	},
	ElvesVenomPlants = {
		files = {
			"kro_sfx_poisonplant_discharge[conacido]_B.ogg",
			"kro_sfx_poisonplant_ready_v2B.ogg",
		},
	},
	ElvesWhiteTree = {
		files = {
			"kro_sfx_bitteringrancor_whitetree-activate.ogg",
			"kro_sfx_bitteringrancor_whitetree-tap.ogg",
		},
	},
	EndlessGnollSounds = {
		files = {
			"kro_sfx_ambience_wardrums[op1].ogg",
			"kro_sfx_ambience_wardrums[op2].ogg",
			"kro_sfx_ambience_wardrums[op3].ogg",
			"kro_sfx_creep_death[op1].ogg",
			"kro_sfx_creep_doublesword[op1].ogg",
			"kro_sfx_heehaw_call[op2].ogg",
			"kro_sfx_heehaw_netfalling_v2[op3].ogg",
			"kro_sfx_heehaw_nethitsfloor.ogg",
		},
	},
	EndlessTwilightSounds = {
		files = {
			"kro_sfx_ainyl_disable.ogg",
			"kro_sfx_ainyl_shield.ogg",
			"kro_sfx_ainyl_teleport[op2].ogg",
			"kro_sfx_bannerbearer_death[op1-SD].ogg",
			"kro_sfx_twlightinvasionambience-2.ogg",
			"kro_sfx_twlightinvasionambience-3.ogg",
		},
	},
	FaerieGroveAmbienceSounds = {
		files = {
			"kro_sfx_ambience_windandowls1.ogg",
		},
	},
	FaerieGroveAmbienceSoundsTenEleven = {
		files = {
			"kro_sfx_ambience_branchesandfaery1.ogg",
			"kro_sfx_ambience_branchesandfaery2.ogg",
		},
	},
	HeroReinforcement = {
		files = {
			"Level_up.ogg",
			"Motumbo_charge_special.ogg",
			"Motumbo_hit.ogg",
			"Motumbo_jump_special.ogg",
			"Reinforcement-02c.ogg",
			"Reinforcement-03c.ogg",
			"Reinforcement-04b.ogg",
			"Reinforcement-Death_c.ogg",
		},
	},
	MetropolisAmbienceSounds = {
		files = {
			"kro_sfx_ambience_winds[op1].ogg",
			"kro_sfx_ambience_winds[op2].ogg",
		},
	},
	common = {
		keep = true,
		files = {
			"Arivan_Confirm04-01a.ogg",
			"Bravebark-confirm_04d.ogg",
			"Bruce_confirm[2]-04c.ogg",
			"Catha_Confirm-02a.ogg",
			"Durax_04c[wet].ogg",
			"Eridan_Confirm-03b.ogg",
			"Faustus-confirm_01b2.ogg",
			"GUITransitionClose.ogg",
			"GUITransitionOpen.ogg",
			"Gyro_confirm-01c.ogg",
			"Level_up.ogg",
			"Lilith_confirm-01d[wet].ogg",
			"Lynn_confirm_01a.ogg",
			"Phoenix2-death_01b.ogg",
			"PrinceDenas-confirm_04a.ogg",
			"RazzAndRags_02b.ogg",
			"Reg'son-confirm_04a.ogg",
			"Reinforcements_01b.ogg",
			"Reinforcements_02a.ogg",
			"Reinforcements_03c.ogg",
			"Sound_AchievementWin.ogg",
			"Sound_ArrowHit2.ogg",
			"Sound_ArrowHit3.ogg",
			"Sound_ArrowRelease2.ogg",
			"Sound_ArrowRelease3.ogg",
			"Sound_BattleAxe.ogg",
			"Sound_Bomb1.ogg",
			"Sound_Coins.ogg",
			"Sound_CommonAreaHit.ogg",
			"Sound_EnemyBigDead.ogg",
			"Sound_EnemyExplode1.ogg",
			"Sound_EnemyGoblinDead.ogg",
			"Sound_EnemyHealing.ogg",
			"Sound_EnemyOrcDead.ogg",
			"Sound_EnemyPuffDead.ogg",
			"Sound_EnemySkeletonBreak2.ogg",
			"Sound_EnemyTrollDead.ogg",
			"Sound_EngineerShot.ogg",
			"Sound_FireballHit.ogg",
			"Sound_FireballUnleash.ogg",
			"Sound_GUIButtonCommon.ogg",
			"Sound_GUIBuyUpgrade.ogg",
			"Sound_GUIMouseOverTowerIcon.ogg",
			"Sound_GUIOpenTowerMenu.ogg",
			"Sound_HumanDead1.ogg",
			"Sound_HumanDead2.ogg",
			"Sound_HumanDead3.ogg",
			"Sound_HumanDead4.ogg",
			"Sound_LooseLife.ogg",
			"Sound_MageShot.ogg",
			"Sound_MapNewFlag.ogg",
			"Sound_MapRoad.ogg",
			"Sound_NextWaveReady.ogg",
			"Sound_NotificationClose.ogg",
			"Sound_NotificationOpen.ogg",
			"Sound_NotificationPaperOver.ogg",
			"Sound_NotificationSecondLevel.ogg",
			"Sound_QuestCompleted.ogg",
			"Sound_QuestFailed.ogg",
			"Sound_RallyPointPlaced.ogg",
			"Sound_RocketLaunt.ogg",
			"Sound_Shootgun.ogg",
			"Sound_Shrapnel.ogg",
			"Sound_Sniper.ogg",
			"Sound_Sorcerer.ogg",
			"Sound_SpellRefresh.ogg",
			"Sound_SpellSelect.ogg",
			"Sound_SpiderAttack1.ogg",
			"Sound_SpiderAttack2.ogg",
			"Sound_TowerBuilding.ogg",
			"Sound_TowerOpenDoor.ogg",
			"Sound_TowerSell.ogg",
			"Sound_WaveIncoming.ogg",
			"Sound_WinStars.ogg",
			"Sound_WolfAttack.ogg",
			"Sound_WolfAttack2.ogg",
			"Veznan-confirm_03_custom_fb.ogg",
			"Xin-confirm_02b.ogg",
			"inapp_cash.ogg",
			"inapp_chin.ogg",
			"inapp_gems.ogg",
			"inapp_gnome.ogg",
			"kre_sfx_arivan_fireballhit_v3.ogg",
			"kro_sfx_inapp-handofmidas-active[op3]C.ogg",
			"kro_sfx_inapp-handofmidas[op1].ogg",
			"kro_sfx_inapp-tearofelynie_v2[conlacrimosa].ogg",
			"kro_sfx_inapp-teleportgem_v2[enemiesin].ogg",
			"kro_sfx_inapp-teleportgem_v2[enemiesout].ogg",
			"kro_sfx_inapp-teleportscroll_v2[sinslam].ogg",
			"kro_sfx_inapp_hornofheroism[op2].ogg",

			"Bonehart-02b_WET.ogg",
			"alric_taunt_confirm_2.ogg",
			"Monk_02b.ogg",
			"dwarf_taunt_1.ogg",
			"dwarf_taunt_2.ogg",
			"dwarfBarracks_taunt_1.ogg",
			"kre_sfx_catha_fairydust.ogg",
			"Holy-Paladin-01c.ogg",
			"kro_sfx_xin_pandamonium-hit1_v1.ogg",
			"kro_sfx_xin_pandamonium-hit2_v1.ogg",
			"kro_sfx_xin_pandamonium_[op1].ogg",
			"kro_sfx_xin_tele-in_v3[op1].ogg",
			"kro_sfx_xin_tele-out_v3.ogg",
			"kro_sfx_faustus_liquidfire_v2_sinchimes.ogg",
			"kro_sfx_faustus_activate[op2].ogg",
			"Drow_01c.ogg",
			"Drow_02c.ogg",
			"Drow_03b.ogg",
			"kro_sfx_ambience_spiders_v2[op1].ogg",
		
			"kro_sfx_inapp_hornofheroism[op2].ogg",

			--HeroPaladin
			"Holy-Paladin-02c.ogg",
			"Holy-Paladin-03b.ogg",
			"Holy-Paladin-04a.ogg",
			"Holy-Paladin-Death_b.ogg",
			"Paladin_deflect.ogg",
			"Paladin_shield_buff.ogg",
			--HeroMonk
			"Hero_Monk_Counter.ogg",
			"Hero_Monk_Firedragon.ogg",
			"Hero_Monk_Hadoken.ogg",
			"Hero_Monk_Multihit_punch.ogg",
			"Hero_Monk_Multihit_scream_1.ogg",
			"Hero_Monk_Multihit_scream_2.ogg",
			"Hero_Monk_Snake_attack.ogg",
			"Monk_01c.ogg",
			"Monk_03c.ogg",
			"Monk_04b.ogg",
			"Monk_Death.ogg",
			--HeroAlric
			"alric_taunt_confirm_1.ogg",
			"alric_taunt_confirm_3.ogg",
			"alric_taunt_confirm_4.ogg",
			"alric_taunt_death.ogg",
			"hero_alric_flurry.ogg",
			"hero_alric_sandwarrior.ogg",
			--HeroDracolich 
			"Bonehart-01a_WET.ogg",
			"Bonehart-03b_WET.ogg",
			"Bonehart-04c_WET.ogg",
			"Bonehart-Death01c_WET.ogg",
			"halloween_bonedragon_attack.ogg",
			"halloween_bonedragon_bonerain.ogg",
			"halloween_bonedragon_kamikaze2.ogg",
			"halloween_bonedragon_respawn_simple.ogg",
			"halloween_bonedragon_soulsplague.ogg",
			"halloween_bonedragon_spawn_congrowl.ogg",

			"kro_sfx_gnome_desintegrate_v2[comic].ogg",
			"kro_sfx_gnome_poison_v2[confrasco].ogg",
			"kro_sfx_gnome_polymorf[conchimes].ogg",
			"kro_sfx_gnome_polymorf[conchimes].ogg",
			"kro_sfx_veznan_teleport_v1.ogg",
			"Gnome_01d.ogg",
			"Gnome_02a.ogg",
			"Awok_01b.ogg",
			"Awok_02c.ogg",
			"kro_sfx_faerydragon_attack[solocristalizacion].ogg",
			"kro_sfx_faerydragon_buydragon[op1].ogg",
			"kro_sfx_faerydragon_extraability[solochimes].ogg",
			"kro_sfx_faerydragon_sfx_attack[op2][soloattack]_B.ogg",
			"kro_sfx_bastion_shot[op1]_modif.ogg",
			"GalhadriansBastion-01c.ogg",
			"GalhadriansBastion-02c.ogg",
			"kro_sfx_ashbite_confirm_v1[op1].ogg",
			"kro_sfx_ashbite_confirm_v1[op2].ogg",

			"dwarfArcher_taunt_1.ogg",
			"dwarfArcher_taunt_2.ogg",
			"Pirate_Tower_01a.ogg",
			"Pirate_Tower_02b.ogg",
			"pirate_taunt_1.ogg",
			"pirate_taunt_2.ogg",
			"pirate_taunt_3.ogg",
			"Pirate_Big_01c.ogg",
			"Pirate_Big_02c.ogg",
			"Elf_Taun1.ogg",
			"Elf_Taun2.ogg",
			"amazon_taunt_1.ogg",
			"amazon_taunt_2.ogg",
			"legionnaire_taunt_2.ogg",
			"legionnaire_taunt_1.ogg",
			"genie_taunt_1.ogg",
			"genie_taunt_2.ogg",
			"FrankyTower-01d.ogg",
			"FrankyTower-02f.ogg",
			"FrankyTower-03c.ogg",
			"FrankyTower-04a.ogg",
			"halloween_tesla_charge.ogg",

			"Sound_TowerSoldierSasquashRally.ogg",
			"Sound_TowerSoldierSasquashReady.ogg",

			--三代英雄语音
			"Female-Elven-Archer-01c.ogg",
			"Female-Elven-Archer-02c.ogg",
			"Female-Elven-Archer-03a.ogg",
			"Female-Elven-Archer-04b.ogg",
			"Female-Elven-Archer-Death_a.ogg",
			"Arivan_Confirm-01b.ogg",
			"Arivan_Confirm-02c.ogg",
			"Arivan_Confirm-03a.ogg",
			"Arivan_Death-01a.ogg",
			"kre_sfx_arivan_elementalstorm_v2_op3.ogg",
			"kre_sfx_arivan_fireballhit_v3.ogg",
			"kre_sfx_arivan_fireballshot_v2.ogg",
			"kre_sfx_arivan_fireballsummon[op2].ogg",
			"kre_sfx_arivan_icebolt[hit].ogg",
			"kre_sfx_arivan_iceboltshot_v2[contono].ogg",
			"kre_sfx_arivan_lightningbolt_v2.ogg",
			"kre_sfx_arivan_stonesummon_v2.ogg",
			"Motumbo_charge_special.ogg",
			"Motumbo_hit.ogg",
			"Motumbo_jump_special.ogg",
			"Reinforcement-01a.ogg",
			"Reinforcement-02c.ogg",
			"Reinforcement-03c.ogg",
			"Reinforcement-04b.ogg",
			"Reinforcement-Death_c.ogg",
			"VarlBerserker_confirm-01a.ogg",
			"VarlBerserker_confirm-02a.ogg",
			"VarlBerserker_confirm-03c.ogg",
			"VarlBerserker_confirm-04a.ogg",
			"VarlBerserker_death-01c.ogg",
			"kro_sfx_bolverk_bearcry[op1].ogg",
			"kro_sfx_bolverk_doubleslash[gore].ogg",
			"Bruce_confirm[2]-01b.ogg",
			"Bruce_confirm[2]-02c.ogg",
			"Bruce_confirm_03d.ogg",
			"Bruce_death[2]-01g.ogg",
			"kro_sfx_bruce_griveousbites.ogg",
			"kro_sfx_bruce_guardianlions-hit[loop-end].ogg",
			"kro_sfx_bruce_guardianlions-hit[loop-start].ogg",
			"kro_sfx_bruce_guardianlions[loop-v2-op1].ogg",
			"kro_sfx_bruce_guardianlions[spell+roar].ogg",
			"kro_sfx_bruce_kingsroar[op1-conimpacto].ogg",
			"Catha_Confirm-01c.ogg",
			"Catha_Confirm-03c.ogg",
			"Catha_Confirm-04d.ogg",
			"Catha_Death-01c.ogg",
			"kre_sfx_catha_fairydust.ogg",
			"kre_sfx_catha_fairyfury[hit]_v2.ogg",
			"kre_sfx_catha_fairyfury[summon].ogg",
			"kre_sfx_catha_fairysoul_v1.ogg",
			"kre_sfx_catha_fairytale[death].ogg",
			"kre_sfx_catha_fairytale[summon].ogg",
			"Eridan_Death-01a.ogg",
			"Kingsguard_01d.ogg",
			"Kingsguard_02c.ogg",
			"PrinceDenas-confirm_01a.ogg",
			"PrinceDenas-confirm_02c.ogg",
			"PrinceDenas-confirm_03b.ogg",
			"PrinceDenas-death_01a.ogg",
			"kro_sfx_princedenas_celebrity_v1[severalshots].ogg",
			"kro_sfx_princedenas_mighty_v3[convoz_op3].ogg",
			"kro_sfx_princedenas_sybarite_v1[op1].ogg",
			"kro_sfx_princedenas_wealthy_v1[op2].ogg",
			"Durax_01a[wet].ogg",
			"Durax_02a[wet].ogg",
			"Durax_03a[wet].ogg",
			"kro_sfx_durax_armblade.ogg",
			"kro_sfx_durax_crystallites.ogg",
			"kro_sfx_durax_death[op1].ogg",
			"kro_sfx_durax_lethalprism_shot_v2.ogg",
			"kro_sfx_durax_movement[loop_end].ogg",
			"kro_sfx_durax_movement[loop_op1].ogg",
			"kro_sfx_durax_movement[loop_op1].ogg",
			"kro_sfx_durax_shardspear[impact].ogg",
			"kro_sfx_durax_shardspear[throw].ogg",
			"kro_sfx_durax_ultimate.ogg",
			"Eridan_Death-01a.ogg",
			"Reg'son-confirm_01a.ogg",
			"Reg'son-confirm_02c.ogg",
			"Reg'son-confirm_03d.ogg",
			"Reg'son-death_01c.ogg",
			"kro_sfx_regson_bladescast_v3[conenergia].ogg",
			"kro_sfx_regson_bladescast_v3[sinenergia].ogg",
			"kro_sfx_regson_slash_v1.ogg",
			"kro_sfx_regson_vindicator_v3.ogg",
			"Eridan_Confirm-01d.ogg",
			"Eridan_Confirm03-01a.ogg",
			"Eridan_Death-01a.ogg",
			"Eridan_confirmextra-01a.ogg",
			"kre_sfx_eridan_doublestrike_v2[mid].ogg",
			"kre_sfx_eridan_nimblefencing.ogg",
			"Faustus-confirm_02b2.ogg",
			"Faustus-confirm_03a2.ogg",
			"Faustus-confirm_04b2.ogg",
			"Faustus-death_01e2.ogg",
			"kro_sfx_faustus_activate[op2].ogg",
			"kro_sfx_faustus_enervation_v2_[op1].ogg",
			"kro_sfx_faustus_fireloop_v1.ogg",
			"kro_sfx_faustus_liquidfire_v2_sinchimes.ogg",
			"kro_sfx_faustus_normalattack_v1.ogg",
			"kro_sfx_faustus_teleport_v1[sinarpa].ogg",
			"kro_sfx_veznan_faustus_killray_v3.ogg",
			"Bravebark-confirm_01c.ogg",
			"Bravebark-confirm_02b.ogg",
			"Bravebark-confirm_03d.ogg",
			"Bravebark-death_01a.ogg",
			"kre_sfx_hyena_specialstomp.ogg",
			"kro_sfx_bravebark_branchball_v1[op1].ogg",
			"kro_sfx_bravebark_healing_v1.ogg",
			"kro_sfx_bravebark_oakseeds_v1.ogg",
			"kro_sfx_bravebark_rootspikes_v1.ogg",
			"kro_sfx_bravebark_teleport-in_v1.ogg",
			"kro_sfx_bravebark_teleport-out_v1.ogg",
			"kro_sfx_bravebark_v2[spikesbajos].ogg",
			"Gyro_confirm-02c.ogg",
			"Gyro_confirm-03c.ogg",
			"Gyro_confirm-04b.ogg",
			"Gyro_death-01d.ogg",
			"kro_sfx_wilbur_attack[concasquillos].ogg",
			"kro_sfx_wilbur_bombsmarch[op1].ogg",
			"kro_sfx_wilbur_boombox.ogg",
			"kro_sfx_wilbur_boombox_box.ogg",
			"kro_sfx_wilbur_calldrones.ogg",
			"kro_sfx_wilbur_dronesattack[metralla]_cut.ogg",
			"kro_sfx_wilbur_smokespit.ogg",
			"Lilith_confirm-02d[wet].ogg",
			"Lilith_confirm-03f[wet].ogg",
			"Lilith_confirm-04a[wet].ogg",
			"Lilith_death-01a[wet].ogg",
			"kro_sfx_lilith_infernalwheel.ogg",
			"kro_sfx_lilith_reaperharvest.ogg",
			"kro_sfx_lilith_resurrection[op2-conchime].ogg",
			"kro_sfx_lilith_soulreaper[op1].ogg",
			"kro_sfx_lilith_ultimate[darkangels-cast].ogg",
			"kro_sfx_lilith_ultimate[darkangels-hit].ogg",
			"kro_sfx_lilith_ultimate[meteors-impact-op1_singlehit].ogg",
			"kro_sfx_veznan_range_shoot_v1.ogg",
			"Lynn_confirm_02c.ogg",
			"Lynn_confirm_03a.ogg",
			"Lynn_confirm_04d.ogg",
			"Lynn_death_01b.ogg",
			"kro_sfx_bitteringrancor_lynn-curseofdispair[conprecarga].ogg",
			"kro_sfx_bitteringrancor_lynn-fatesealed.ogg",
			"kro_sfx_bitteringrancor_lynn-hexfury[op3].ogg",
			"kro_sfx_bitteringrancor_lynn-weakeningcurse[sincrackle].ogg",
			"Phoenix2-death_01a.ogg",
			"Phoenix2-death_01a.ogg",
			"kro_sfx_phoenix_basicattack.ogg",
			"kro_sfx_phoenix_blazingoffspring_hit_v2.ogg",
			"kro_sfx_phoenix_blazingoffspring_shot[op1].ogg",
			"kro_sfx_phoenix_eggexplosion.ogg",
			"kro_sfx_phoenix_fireegg_activate_v2.ogg",
			"kro_sfx_phoenix_fireegg_v3.ogg",
			"kro_sfx_phoenix_immolation_v2.ogg",
			"kro_sfx_phoenix_ringoffire_explode_v2.ogg",
			"kro_sfx_phoenix_ringoffire_spawn[op2].ogg",
			"RazzAndRags-death_01a.ogg",
			"RazzAndRags_01b.ogg",
			"RazzAndRags_03d.ogg",
			"RazzAndRags_04c.ogg",
			"kro_sfx_angrygnome_objectspawn[op2].ogg",
			"kro_sfx_gnome_kamihare[sinpops].ogg",
			"kro_sfx_gnome_shot[op1_conchime].ogg",
			"kro_sfx_hammertime[op1_12bits].ogg",
			"kro_sfx_hammertime[op2].ogg",
			"kro_sfx_raggified_attack.ogg",
			"kro_sfx_raggified_groundstomp[medium].ogg",
			"kro_sfx_raggified_transform[op2].ogg",
			"Veznan-confirm_01e.ogg",
			"Veznan-confirm_02f.ogg",
			"Veznan-confirm_04_custom_ec.ogg",
			"Veznan_death-[new]01b.ogg",
			"kro_sfx_veznan_arcanenova_v1.ogg",
			"kro_sfx_veznan_darkpact_v1.ogg",
			"kro_sfx_veznan_demondeath_v3.ogg",
			"kro_sfx_veznan_demonfireball_hit_v3.1.ogg",
			"kro_sfx_veznan_demonfireball_throw_v3.ogg",
			"kro_sfx_veznan_magicshackles_v1[op2]-01.ogg",
			"kro_sfx_veznan_range_shoot_v1.ogg",
			"kro_sfx_veznan_soulburn_v8[sinimpacto].ogg",
			"kro_sfx_veznan_teleport_v1.ogg",
			"Xin-confirm_01c.ogg",
			"Xin-confirm_03a.ogg",
			"Xin-confirm_04c.ogg",
			"Xin-death_01a.ogg",
			"kro_sfx_xin_daringstrikehit_v1.ogg",
			"kro_sfx_xin_inspire_v3[op1].ogg",
			"kro_sfx_xin_mindoverbody.ogg",
			"kro_sfx_xin_pandamonium-hit1_v1.ogg",
			"kro_sfx_xin_pandamonium-hit2_v1.ogg",
			"kro_sfx_xin_pandamonium_[op1].ogg",
			"kro_sfx_xin_pandastyle_v3[op2].ogg",
			"kro_sfx_xin_polehit1_v3[conhoo].ogg",
			"kro_sfx_xin_polehit2_v3[conhoo].ogg",
			"kro_sfx_xin_tele-in_v3[op1].ogg",
			"kro_sfx_xin_tele-out_v3.ogg",
			--二代英雄
			"PirateBoat_01c.ogg",
			"PirateBoat_02c.ogg",
			"PirateBoat_03a.ogg",
			"dwarfHero_taunt_confirm_1.ogg",
			"dwarfHero_taunt_confirm_2.ogg",
			"dwarfHero_taunt_confirm_3.ogg",
			"dwarfHero_taunt_death.ogg",
			"Vampiress-01c.ogg",
			"Vampiress-02c.ogg",
			"Vampiress-03c.ogg",
			"halloween_vampiress_areaattack_confilo.ogg",
			"Vampiress-Death02c.ogg",
			"halloween_vampiress_drainlifeOP2.ogg",
			"assassinHero_taunt_confirm_1.ogg",
			"assassinHero_taunt_confirm_2.ogg",
			"assassinHero_taunt_confirm_3.ogg",
			"assassinHero_taunt_confirm_4.ogg",
			"hero_mirage_lethalstrike_hit.ogg",
			"hero_mirage_lethalstrike_vanish.ogg",
			"hero_mirage_shadowdance_cast.ogg",
			"hero_mirage_shadowdance_hit.ogg",
			"hero_mirage_shadowdodge.ogg",
			"hero_mirage_shadowdodge_puff.ogg",
			"assassinHero_taunt_death.ogg",
			"giant_taunt_confirm_1.ogg",
			"giant_taunt_confirm_2.ogg",
			"giant_taunt_confirm_3.ogg",
			"giant_taunt_confirm_4.ogg",
			"giant_taunt_death.ogg",
			"hero_grawl_bigpunch.ogg",
			"hero_grawl_boulder_hit.ogg",
			"hero_grawl_boulder_throw.ogg",
			"hero_grawl_stomp.ogg",
			"hero_nivus_attack.ogg",
			"hero_nivus_desintegrate.ogg",
			"hero_nivus_magicmissile_hit.ogg",
			"hero_nivus_magicmissile_summon.ogg",
			"hero_nivus_teleport.ogg",
			"wizzard_taunt_confirm_1.ogg",
			"wizzard_taunt_confirm_2.ogg",
			"wizzard_taunt_confirm_3.ogg",
			"wizzard_taunt_confirm_4.ogg",
			"wizzard_taunt_death.ogg",
			"beastmaster_taunt_confirm_1.ogg",
			"beastmaster_taunt_confirm_2.ogg",
			"beastmaster_taunt_confirm_3.ogg",
			"beastmaster_taunt_confirm_4.ogg",
			"beastmaster_taunt_death.ogg",
			"hero_beastmaster_bird_attack.ogg",
			"hero_beastmaster_jabali_attack2.ogg",
			"hero_beastmaster_rhino_stampede.ogg",
			"hero_beastmaster_summon_boar.ogg",
			"hero_beastmaster_summon_rhino.ogg",
			"hero_cronan_whiplash.ogg",
			"alien_taunt_confirm_1.ogg",
			"alien_taunt_confirm_2.ogg",
			"alien_taunt_confirm_3.ogg",
			"alien_taunt_confirm_4.ogg",
			"alien_taunt_death.ogg",
			"hero_alien_abduction.ogg",
			"hero_alien_death_explosion.ogg",
			"hero_alien_disc_bounce.ogg",
			"hero_alien_disc_throw.ogg",
			"hero_alien_drone_call.ogg",
			"hero_alien_drone_leave.ogg",
			"hero_alien_drone_ray_loop.ogg",
			"hero_priest_consecrate.ogg",
			"hero_priest_healing.ogg",
			"hero_priest_teleport.ogg",
			"priest_taunt_confirm_1.ogg",
			"priest_taunt_confirm_2.ogg",
			"priest_taunt_confirm_3.ogg",
			"priest_taunt_confirm_4.ogg",
			"priest_taunt_confirm_5.ogg",
			"priest_taunt_death.ogg",
			"dragonHero_confirm1.ogg",
			"dragonHero_confirm2.ogg",
			"dragonHero_confirm3.ogg",
			"dragonHero_confirm4.ogg",
			"hero_dragon_birth.ogg",
			"hero_dragon_death.ogg",
			"hero_dragon_fireball_explode.ogg",
			"hero_dragon_flamethrower.ogg",
			"hero_dragon_napalm.ogg",
			"hero_dragon_smoke.ogg",
			"hero_dragon_spit.ogg",
			"blackthorne_taunt_confirm_1.ogg",
			"blackthorne_taunt_confirm_2.ogg",
			"blackthorne_taunt_confirm_3.ogg",
			"blackthorne_taunt_confirm_4.ogg",
			"blackthorne_taunt_confirm_5.ogg",
			"blackthorne_taunt_death.ogg",
			"hero_blackthorne_barrel.ogg",
			"hero_blackthorne_kraken.ogg",
			"Hero_Karkinos_Burrow_in.ogg",
			"Hero_Karkinos_Burrow_out.ogg",
			"Hero_Karkinos_Cannon.ogg",
			"Hero_Karkinos_Cannon_explosion.ogg",
			"Hero_Karkinos_Pincer.ogg",
			"Hero_Karkinos_Shield.ogg",
			"Karkinos_01b.ogg",
			"Karkinos_02b.ogg",
			"Karkinos_03d.ogg",
			"Karkinos_04b.ogg",
			"Karkinos_Death.ogg",
			"Dante-01a.ogg",
			"Dante-02a.ogg",
			"Dante-03a.ogg",
			"Dante-04d.ogg",
			"Dante-Death01c.ogg",
			"halloween_helsing_holywater_conquemadura.ogg",
			"halloween_helsing_relic.ogg",
			"KRF_sfx_vodoo_ataqueV3.ogg",
			"KRF_sfx_vodoo_calaveraV3_op2.ogg",
			"KRF_sfx_vodoo_kamikazegolpev3.ogg",
			"KRF_sfx_vodoo_kamikazelanza.ogg",
			"KRF_sfx_vodoo_munieco.ogg",
			"Vodoo_01c.ogg",
			"Vodoo_02b.ogg",
			"Vodoo_03b.ogg",
			"Vodoo_04b.ogg",
			"Vodoo_05d.ogg",
			"KRF_sfx_minotauro_ataquefuerte.ogg",
			"KRF_sfx_minotauro_carga.ogg",
			"KRF_sfx_minotauro_grito.ogg",
			"KRF_sfx_minotauro_portal.ogg",
			"KRF_sfx_minotauro_remolino_2tiempo.ogg",
			"Minotaur_01b.ogg",
			"Minotaur_02c.ogg",
			"Minotaur_03c.ogg",
			"Minotaur_04b.ogg",
			"Minotaur_05e_death.ogg",
			"Saitam-confirm_01b[2].ogg",
			"Saitam-death_01b[2].ogg",
			"Saitam_confirm-03c.ogg",
			"Saitam_confirm-04c.ogg",
			"Saitam_confirm-05c.ogg",
			"Saitam-confirm_02c[2].ogg",
			"krf_toee_saitam_angrygod[flames-loop].ogg",
			"krf_toee_saitam_angrygod[scream].ogg",
			"krf_toee_saitam_attack[op1].ogg",
			"krf_toee_saitam_attack[op2].ogg",
			"krf_toee_saitam_cloudclimb_v2[op2].ogg",
			"krf_toee_saitam_clouddrop.ogg",
			"krf_toee_saitam_cloudtransport.ogg",
			"krf_toee_saitam_monkeypalm[op1].ogg",
			"krf_toee_saitam_polespin[loop-end].ogg",
			"krf_toee_saitam_polespin[loop].ogg",
			"krf_toee_saitam_tetsubostorm[op1].ogg",
			"Explosion_water.ogg",
			--1代英雄
			"Aleria_special_arrow.ogg",
			"Aleria_sumon.ogg",
			"Aleria_wildcat_hit.ogg",
			"Dwarf-Rifleman-01a.ogg",
			"Dwarf-Rifleman-02c.ogg",
			"Dwarf-Rifleman-03c.ogg",
			"Dwarf-Rifleman-04c.ogg",
			"Dwarf-Rifleman-Death_c.ogg",
			"Dwarf_brea_shot2.ogg",
			"Dwarf_brea_shot_hit.ogg",
			"Dwarf_mine.ogg",
			"Mage_blue_rain_charge.ogg",
			"Mage_blue_rain_drop.ogg",
			"Mage_shadows.ogg",
			"Young-Mage-01d.ogg",
			"Young-Mage-02a.ogg",
			"Young-Mage-03c.ogg",
			"Young-Mage-04c.ogg",
			"Young-Mage-Death_c.ogg",
			"Cinder_special_area.ogg",
			"Cinder_special_fireball_1_start.ogg",
			"Cinder_special_fireball_2_end.ogg",
			"Elemental-01c.ogg",
			"Elemental-02c.ogg",
			"Elemental-03b.ogg",
			"Elemental-04c.ogg",
			"Elemental-Death_c.ogg",
			"KingDenas-01d.ogg",
			"KingDenas-02d.ogg",
			"KingDenas-03g.ogg",
			"KingDenas-04e.ogg",
			"KingDenas-05c.ogg",
			"KingDenas_sfx_attack.ogg",
			"KingDenas_sfx_order1.ogg",
			"KingDenas_sfx_order3.ogg",
			"Viking-01b.ogg",
			"Viking-02c.ogg",
			"Viking-03b.ogg",
			"Viking-04c.ogg",
			"Viking-Death_01d.ogg",
			"Viking_Call.ogg",
			"Viking_Hit.ogg",
			"Viking_StartAttack.ogg",
			"Viking_Transform.ogg",
			"Elora_GroundFreeze.ogg",
			"Elora_IceShard.ogg",
			"Elora_IceShardBreak.ogg",
			"Elora_IceShardSummon.ogg",
			"Frost-Mage-01a.ogg",
			"Frost-Mage-02c.ogg",
			"Frost-Mage-03d.ogg",
			"Frost-Mage-04a.ogg",
			"Frost-Mage-Death_01c.ogg",
			"Oni-01c.ogg",
			"Oni-02c.ogg",
			"Oni-03c.ogg",
			"Oni-04a.ogg",
			"Oni-Death01a.ogg",
			"inferno_oni_groundSwords.ogg",
			"inferno_oni_instakill.ogg",
			"Hacksaw-01c.ogg",
			"Hacksaw-02c.ogg",
			"Hacksaw-03a.ogg",
			"Hacksaw-04a.ogg",
			"Hacksaw-Death01c.ogg",
			"inferno_lumberjack_drill.ogg",
			"inferno_lumberjack_shootSaw.ogg",
			"KR_sfx_thor_ataqueelectrico.ogg",
			"KR_sfx_thor_lanzamartillo_op2.ogg",
			"KR_sfx_thor_muerte.ogg",
			"KR_sfx_thor_thunder.ogg",
			"Thor_01a.ogg",
			"Thor_02a.ogg",
			"Thor_03c.ogg",
			"Thor_04c.ogg",
			"Thor_05c.ogg",
			"TenShi_02c.ogg",
			"TenShi_01c_and_a.ogg",
			"TenShi_01a_mmh.ogg",
			"TenShi_buffed_01c.ogg",
			"TenShi_buffed_02b.ogg",
			"TenShi_buffed_01a_laugh_only.ogg",
			"TenShi_respawn_01d.ogg",
			"TenShi_transformation_01d.ogg",
			"TenShi_transformation_02c.ogg",
			"kr1_sfx_tenshi_basicAttack1_var1_v1.ogg",
			"kr1_sfx_tenshi_basicAttack1_var2_v1.ogg",
			"kr1_sfx_tenshi_basicAttack1_var3_v1.ogg",
			"kr1_sfx_tenshi_attack2_v1.ogg",
			"kr1_sfx_tenshi_rainOfFire_start_mix.ogg",
			"kr1_sfx_tenshi_rainOfFire_loop-End_v1_10db.ogg",
			"kr1_sfx_tenshi_buffedSpinAttack_2hits_v1.ogg",
			"kr1_sfx_tenshi_buffedSpinAttack_3hits_v1.ogg",
			"kr1_sfx_tenshi_buffedBombAttack_3hits_v1_op2.ogg",
			"kr1_sfx_tenshi_buffedBombAttack_6hits_v1_op2.ogg",
			"kr1_sfx_tenshi_transformToBuffed_op1_v1.ogg",
			"kr1_sfx_tenshi_transformToNormal_v1.ogg",
			"kr1_sfx_tenshi_death_v1.ogg",
			"kr1_sfx_tenshi_teleport_v1_15db.ogg",
			"canibal_eating.ogg",
			"canibal_necromancer.ogg",
			"canibal_zombie_one.ogg",
			"canibal_zombie_three.ogg",
			"canibal_zombie_two.ogg",
			"savant_attack.ogg",
---魔法花
			"kre_sfx_plant_magicmissile.ogg",
			"kre_sfx_plant_ready_conchime.ogg",
---紫魔法花
			"kro_sfx_poisonplant_discharge[conacido]_B.ogg",
			"kro_sfx_poisonplant_ready_v2B.ogg",
---树
			"kro_sfx_bitteringrancor_lynn-curseofdispair[conprecarga].ogg",
			"kro_sfx_bitteringrancor_lynn-fatesealed.ogg",
			"kro_sfx_bitteringrancor_lynn-hexfury[op3].ogg",
			"kro_sfx_bitteringrancor_lynn-weakeningcurse[sincrackle].ogg",
						
			"kro_sfx_barezad_firebreath_v2[loop].ogg",
			"kro_sfx_barezad_firebreath_v2[end].ogg",
			"kro_sfx_barezad_firebreath_v2[starter].ogg",
			"kro_sfx_barezad_fly[loop-op2].ogg"
		},
		ids = {},
	},
}
