return{
    common4 = {
        files = {
            "Mapa.ogg",
            "kr4_elves_barrack_taunt_1.ogg",
            "kr4_elves_barrack_taunt_2.ogg",
            "kr4_elves_barrack_taunt_3.ogg",
            "kr4_elves_barrack_taunt_4.ogg",
            "kr4_dark_army_blazing_mage_taunt_1.ogg",
            "kr4_dark_army_blazing_mage_taunt_2.ogg",
            "kr4_dark_army_blazing_mage_taunt_3.ogg",
            "kr4_dark_army_blazing_mage_taunt_4.ogg",
            "kr4_dinos_ignis_altar_build_taunt_1.ogg",
            "kr4_dinos_ignis_altar_build_taunt_2.ogg",
            "kr4_dinos_ignis_altar_build_taunt_3.ogg",
            "kr4_dinos_ignis_altar_build_taunt_4.ogg",
            "kr4_dark_army_archer_taunt_4.ogg",
		    "kr4_dark_army_archer_taunt_1.ogg",
		    "kr4_dark_army_archer_taunt_2.ogg",
		    "kr4_dark_army_archer_taunt_3.ogg",
            "kr4_dark_army_barrack_taunt_4.ogg",
		    "kr4_dark_army_barrack_taunt_1.ogg",
		    "kr4_dark_army_barrack_taunt_2.ogg",
		    "kr4_dark_army_barrack_taunt_3.ogg",
            "kr4_dark_army_melting_furnance_taunt_4.ogg",
			"kr4_dark_army_melting_furnance_taunt_1.ogg",
			"kr4_dark_army_melting_furnance_taunt_2.ogg",
			"kr4_dark_army_melting_furnance_taunt_3.ogg",
            "kr4_warmonger_archer_taunt_4.ogg",
			"kr4_warmonger_archer_taunt_1.ogg",
			"kr4_warmonger_archer_taunt_2.ogg",
			"kr4_warmonger_archer_taunt_3.ogg",
            "kr4_ember_lords_mage_taunt_4.ogg",
			"kr4_ember_lords_mage_taunt_1.ogg",
			"kr4_ember_lords_mage_taunt_2.ogg",
			"kr4_ember_lords_mage_taunt_3.ogg",
            "kr_voice_ogreshipwreck_lvl1_b.ogg",
            "kr_voice_ogreshipwreck_lvl2_a.ogg",
            "kr_voice_ogreshipwreck_lvl3_b.ogg",
            "kr_voice_ogreshipwreck_lvl4_b.ogg",
            "kr4_fallen_ones_spirit_mausoleum_taunt_1.ogg",
			"kr4_fallen_ones_spirit_mausoleum_taunt_2.ogg",
			"kr4_fallen_ones_spirit_mausoleum_taunt_3.ogg",
			"kr4_fallen_ones_spirit_mausoleum_taunt_4.ogg",
            "kr4_shaolin_temple_taunt_1.ogg",
			"kr4_shaolin_temple_taunt_2.ogg",
			"kr4_shaolin_temple_taunt_3.ogg",
			"kr4_shaolin_temple_taunt_4.ogg",
            "kr4_rotten_forest_build_taunt_1.ogg",
			"kr4_rotten_forest_build_taunt_2.ogg",
			"kr4_rotten_forest_build_taunt_3.ogg",
			"kr4_rotten_forest_build_taunt_4.ogg",
            "kr4_wicked_sisters_build_taunt_1.ogg",
            "kr4_wicked_sisters_build_taunt_2.ogg",
            "kr4_wicked_sisters_build_taunt_3.ogg",
            "kr4_wicked_sisters_build_taunt_4.ogg",
            "kr4_swamp_monster_taunt_1.ogg",
            "kr4_swamp_monster_taunt_2.ogg",
            "kr4_swamp_monster_taunt_3.ogg",
            "kr4_swamp_monster_taunt_4.ogg",
            "kr4_warmonger_balloon_taunt_1.ogg",
            "kr4_warmonger_balloon_taunt_2.ogg",
            "kr4_warmonger_balloon_taunt_3.ogg",
            "kr4_warmonger_balloon_taunt_4.ogg",
            "kr4_fallen_ones_bone_flingers_taunt_4.ogg",
			"kr4_fallen_ones_bone_flingers_taunt_1.ogg",
			"kr4_fallen_ones_bone_flingers_taunt_2.ogg",
			"kr4_fallen_ones_bone_flingers_taunt_3.ogg",
            "kr4_hero_eiskalt_taunt_1.ogg",
            "kr4_hero_eiskalt_taunt_2.ogg",
            "kr4_hero_eiskalt_taunt_3.ogg",
            "kr4_hero_eiskalt_taunt_4.ogg",
            "kr4_warmonger_barrack_taunt_1.ogg",
			"kr4_warmonger_barrack_taunt_2.ogg",
			"kr4_warmonger_barrack_taunt_3.ogg",
			"kr4_warmonger_barrack_taunt_4.ogg",
            "kr4_warmonger_mage_taunt_4.ogg",
			"kr4_warmonger_mage_taunt_1.ogg",
			"kr4_warmonger_mage_taunt_2.ogg",
			"kr4_warmonger_mage_taunt_3.ogg",
            "kr4_warmonger_rocket_taunt_4.ogg",
			"kr4_warmonger_rocket_taunt_1.ogg",
			"kr4_warmonger_rocket_taunt_2.ogg",
			"kr4_warmonger_rocket_taunt_3.ogg",
            "kr4_fallen_ones_grim_cemetery_taunt_4.ogg",
			"kr4_fallen_ones_grim_cemetery_taunt_1.ogg",
			"kr4_fallen_ones_grim_cemetery_taunt_2.ogg",
			"kr4_fallen_ones_grim_cemetery_taunt_3.ogg",
            "kr4_sfx_tower_tremor_voice_towerConstruction_v1.ogg",
            "kr4_sfx_tower_tremor_voice_towerUpgrade_v1.ogg",
            "kr4_sfx_tower_tremor_voice_towerSkill_v1.ogg",
            "kr4_deep_devils_taunt_1.ogg",
            "kr4_deep_devils_taunt_2.ogg",
            "kr4_deep_devils_taunt_3.ogg",
            "kr4_deep_devils_taunt_4.ogg",
            "kr4_hero_jacko_taunt_1.ogg",
			"kr4_hero_jacko_taunt_2.ogg",
			"kr4_hero_jacko_taunt_3.ogg",
			"kr4_hero_jacko_taunt_4.ogg",
            "kr4_hero_murglun_taunt_1.ogg",
            "kr4_hero_beresad_taunt_1.ogg",
            "kr_voice_lucerna_select01_a.ogg",
            "kr4_hero_tank_taunt_1.ogg",
            "kr4_hero_orc_taunt_1.ogg",
            "kr4_hero_asra_taunt_1.ogg",
            "kr4_hero_oloch_taunt_1.ogg",
        }
    },
    tower_twilight_elves_barrack = {
        files = {
            -- customization
            "Drow_01c.ogg",
            "Drow_02c.ogg",
            "Drow_03b.ogg",
            "kr4_elves_barrack_taunt_1.ogg",
            "kr4_elves_barrack_taunt_2.ogg",
            "kr4_elves_barrack_taunt_3.ogg",
            "kr4_elves_barrack_taunt_4.ogg",
            "kr4_elves_barrack_backstab_upg.ogg",
            "kr4_elves_barrack_multishoot_upg.ogg",
            "kr4_elves_barrack_afterlife_upg.ogg",
            "kr4_elves_eliteharassers_arrowstorm_single1.ogg",
            "kr4_elves_eliteharassers_arrowstorm_single2.ogg",
            "kr4_elves_eliteharassers_arrowstorm_single3.ogg",
            "kr4_elves_eliteharassers_lastbreath1.ogg",
            "kr4_elves_eliteharassers_lastbreath2.ogg",
            
        }
    },
    tower_blazing_watcher = {
        files = {
            "kr4_dark_army_blazing_mage_attack_loop.ogg",
            "kr4_dark_army_blazing_mage_attack_loopend.ogg",
            "kr4_dark_army_blazing_mage_attack_loopstart.ogg",
            "kr4_dark_army_blazing_mage_destructo_upg.ogg",
            "kr4_dark_army_blazing_mage_destructoray.ogg",
            "kr4_dark_army_blazing_mage_explosive_upg.ogg",
            "kr4_dark_army_blazing_mage_power_upg.ogg",
            "kr4_dark_army_blazing_mage_taunt_1.ogg",
            "kr4_dark_army_blazing_mage_taunt_2.ogg",
            "kr4_dark_army_blazing_mage_taunt_3.ogg",
            "kr4_dark_army_blazing_mage_taunt_4.ogg",
            "kr4_dark_army_blazing_mage_unstablepower.ogg",
        }
    },
    tower_ignis_altar = {
        files = {
                "kr4_dinos_ignis_altar_build_taunt_1.ogg",
                "kr4_dinos_ignis_altar_build_taunt_2.ogg",
                "kr4_dinos_ignis_altar_build_taunt_3.ogg",
                "kr4_dinos_ignis_altar_build_taunt_4.ogg",
                "kr4_dinos_ignis_altar_upgrade_elemental.ogg",
                "kr4_dinos_ignis_altar_upgrade_debuff.ogg",
                "kr4_dinos_ignis_altar_upgrade_true_fire.ogg",
                "kra_sfx_tower_arboreanEmissary_basicAttack_var1_v1.ogg",
                "kra_sfx_tower_arboreanEmissary_basicAttack_var3_v1.ogg",
                "kra_sfx_tower_arboreanEmissary_basicAttack_var2_v1.ogg",
        }
    },
    tower_shadow_archer = {
        files = {
        "kr4_dark_army_archer_backstab_upg.ogg",
        "kr4_dark_army_archer_crows_nest_upg.ogg",
        "kr4_dark_army_archer_crows_nest_attack1.ogg",
		"kr4_dark_army_archer_crows_nest_attack2.ogg",
        "kr4_dark_army_archer_shadow_mark_upg.ogg",
        "kr4_dark_army_archer_taunt_4.ogg",
		"kr4_dark_army_archer_taunt_1.ogg",
		"kr4_dark_army_archer_taunt_2.ogg",
		"kr4_dark_army_archer_taunt_3.ogg",
        "kr4_dark_army_archer_shadow_mark.ogg",
        "kr4_dark_army_archer_shadow_mark.ogg",
        "kr4_dark_army_archer_backstab_stab.ogg",
        "kr4_dark_army_archer_backstab_poof.ogg",
        }
    },
    tower_dark_knights = {
        files = {
        "kr4_dark_army_barrack_taunt_4.ogg",
		"kr4_dark_army_barrack_taunt_1.ogg",
		"kr4_dark_army_barrack_taunt_2.ogg",
		"kr4_dark_army_barrack_taunt_3.ogg",
        "kr4_dark_army_barrack_impervious_upg.ogg",
        "kr4_dark_army_barrack_impervious.ogg",
        "kr4_dark_army_barrack_armor_of_thorns_upg.ogg",
        "kr4_dark_army_barrack_brutal_strike_upg.ogg",
        "kr4_dark_army_barrack_brutal_strike.ogg",
        "kr4_dark_army_barrack_brutal_strike_hit.ogg",
        "kr4_generic_combat1.ogg",
		"kr4_generic_combat2.ogg",
		"kr4_generic_combat3.ogg"
        }
    },
    tower_melting_furnace = {
        files = {
            "kr4_dark_army_melting_furnance_carbonroll.ogg",
            "kr4_dark_army_melting_furnance_attack.ogg",
            "kr4_dark_army_melting_furnance_burning_heat.ogg",
            "kr4_dark_army_melting_furnance_hoat_coals.ogg",
            "kr4_dark_army_melting_furnance_abrasive_heat_upg.ogg",
            "kr4_dark_army_melting_furnance_burning_heat_upg.ogg",
            "kr4_dark_army_melting_furnance_hoat_coals_upg.ogg",
            "kr4_dark_army_melting_furnance_taunt_4.ogg",
			"kr4_dark_army_melting_furnance_taunt_1.ogg",
			"kr4_dark_army_melting_furnance_taunt_2.ogg",
			"kr4_dark_army_melting_furnance_taunt_3.ogg",
        }
    },
    tower_goblirang = {
        files = {
            "kr4_warmonger_archer_angry_bees.ogg",
            "kr4_warmonger_archer_angry_bees_upg.ogg",
            "kr4_warmonger_archer_headbang_upg.ogg",
            "kr4_warmonger_archer_rubberangs_upg.ogg",
            "kr4_warmonger_archer_taunt_4.ogg",
			"kr4_warmonger_archer_taunt_1.ogg",
			"kr4_warmonger_archer_taunt_2.ogg",
			"kr4_warmonger_archer_taunt_3.ogg",
            --"Sound_ArrowRelease2.ogg",
            --"Sound_ArrowRelease3.ogg",
        }
    },
    tower_infernal_mage = {
        files = {
            "kr4_ember_lords_mage_taunt_4.ogg",
			"kr4_ember_lords_mage_taunt_1.ogg",
			"kr4_ember_lords_mage_taunt_2.ogg",
			"kr4_ember_lords_mage_taunt_3.ogg",
            "kr4_ember_lords_mage_affliction_upg.ogg",
            "kr4_ember_lords_mage_infernal_teleport_upg.ogg",
            "kr4_ember_lords_mage_overcharge_upg.ogg",
            "kr4_ember_lords_mage_attack.ogg",
            "kr4_ember_lords_mage_overcharge.ogg",
            "kr4_ember_lords_mage_affliction.ogg"
        }
    },
    tower_ogre_shipwreck = {
        files = {
            "kr_voice_ogreshipwreck_lvl1_b.ogg",
            "kr_voice_ogreshipwreck_lvl2_a.ogg",
            "kr_voice_ogreshipwreck_lvl3_b.ogg",
            "kr_voice_ogreshipwreck_lvl4_b.ogg",
            "kr_voice_ogreshipwreck_power01_a.ogg",
            "kr_voice_ogreshipwreck_power02_a.ogg",
            "kr_voice_ogreshipwreck_power03_a.ogg",
            "krv_sfx_tower_ogre_shipwreck_musketRage-Skill_v1.ogg"
        }
    },
    tower_spirit_mausoleum = {
        files = {
            "kr4_fallen_ones_spirit_mausoleum_taunt_1.ogg",
			"kr4_fallen_ones_spirit_mausoleum_taunt_2.ogg",
			"kr4_fallen_ones_spirit_mausoleum_taunt_3.ogg",
			"kr4_fallen_ones_spirit_mausoleum_taunt_4.ogg",
            "kr4_fallen_ones_spirit_mausoleum_communion_upg.ogg",
            "kr4_fallen_ones_spirit_mausoleum_possesion_upg.ogg",
            "kr4_fallen_ones_spirit_mausoleum_gargoyles_upg.ogg",
            "kr4_fallen_ones_spirit_mausoleum_attack_preload.ogg",
            "kr4_fallen_ones_spirit_mausoleum_attack.ogg",
            "kr4_fallen_ones_spirit_mausoleum_possession_cast.ogg",
            "kr4_fallen_ones_spirit_mausoleum_possession_hit.ogg",
        }
    },
    tower_shaolin = {
        files = {
            "kr4_shaolin_temple_taunt_1.ogg",
			"kr4_shaolin_temple_taunt_2.ogg",
			"kr4_shaolin_temple_taunt_3.ogg",
			"kr4_shaolin_temple_taunt_4.ogg",
            "kr4_shaolin_temple_monks_upg.ogg",
            "kr4_shaolin_temple_dragon_warrior_upg.ogg",
            "kr4_shaolin_temple_abundance_upg.ogg",
            "kr4_shaolin_temple_hits_var1.ogg",
        }
    },
    tower_rotten_forest = {
        files = {
            "kr4_rotten_forest_build_taunt_1.ogg",
			"kr4_rotten_forest_build_taunt_2.ogg",
			"kr4_rotten_forest_build_taunt_3.ogg",
			"kr4_rotten_forest_build_taunt_4.ogg",
            "kr4_rotten_forest_ents_upg.ogg",
            "kr4_rotten_forest_mist_upg.ogg",
            "kr4_rotten_forest_branches_upg.ogg",
            "kr4_rotten_forest_attack.ogg",
            "kr4_rotten_forest_rootsevil.ogg",
        }
    },
    tower_wicked_sisters = {
        files = {
            "kr4_wicked_sisters_build_taunt_1.ogg",
            "kr4_wicked_sisters_build_taunt_2.ogg",
            "kr4_wicked_sisters_build_taunt_3.ogg",
            "kr4_wicked_sisters_build_taunt_4.ogg",
            "kr4_wicked_sisters_froggification_upg.ogg",
            "kr4_wicked_sisters_brumstick_upg.ogg",
            "kr4_wicked_sisters_totem_upg.ogg",
            "kr4_wicked_sisters_attack.ogg",
            "kr4_wicked_sisters_froggification.ogg",
            "kr4_sfx_hero_isfet_polymorph_frogOnly_v1.ogg",
        }
    },
    tower_swamp_monster = {
        files = {
            "kr4_swamp_monster_taunt_change.ogg",
            "kr4_swamp_monster_taunt_1.ogg",
            "kr4_swamp_monster_taunt_2.ogg",
            "kr4_swamp_monster_taunt_3.ogg",
            "kr4_swamp_monster_taunt_4.ogg",
            "kr4_swamp_monster_blinding_liquid_upg.ogg",
            "kr4_swamp_monster_smash_upg.ogg",
            "kr4_swamp_monster_carnivore_upg.ogg",
            "kr4_swamp_monster_in.ogg",
            "kr4_swamp_monster_out.ogg",
            "kr4_swamp_monster_explosion.ogg",
            "kr4_swamp_monster_throw.ogg",
        }
    },
    tower_balloon = {
        files = {
            "kr4_warmonger_balloon_taunt_1.ogg",
            "kr4_warmonger_balloon_taunt_2.ogg",
            "kr4_warmonger_balloon_taunt_3.ogg",
            "kr4_warmonger_balloon_taunt_4.ogg",
            "kr4_warmonger_balloon_paratroopers.ogg",
            "kr4_warmonger_balloon_tarbomb.ogg",
            "kr4_warmonger_balloon_forwardParachute_upg.ogg",
            "kr4_warmonger_balloon_forwardSplash_upg.ogg",
            "kr4_warmonger_balloon_forwardAura_upg.ogg",
        }
    },
    tower_bone_flingers = {
        files = {
			"kr4_fallen_ones_bone_flingers_taunt_4.ogg",
			"kr4_fallen_ones_bone_flingers_taunt_1.ogg",
			"kr4_fallen_ones_bone_flingers_taunt_2.ogg",
			"kr4_fallen_ones_bone_flingers_taunt_3.ogg",
			"kr4_fallen_ones_bone_flingers_bone_golem_upg.ogg",
			"kr4_fallen_ones_bone_flingers_calcified_bones_upg.ogg",
			"kr4_fallen_ones_bone_flingers_walking_army_upg.ogg",
			"kr4_fallen_ones_bone_flingers_summon.ogg",

        }
    },
    tower_orc_warriors_den = {
		files = {
			"kr4_warmonger_barrack_taunt_1.ogg",
			"kr4_warmonger_barrack_taunt_2.ogg",
			"kr4_warmonger_barrack_taunt_3.ogg",
			"kr4_warmonger_barrack_taunt_4.ogg",
			"kr4_warmonger_barrack_battlewits_upg.ogg",
			"kr4_warmonger_barrack_seal_of_blood_upg.ogg",
			"kr4_warmonger_barrack_promotion_upg.ogg",
        }
    },
    tower_orc_shaman = {
        files = {
            "kr4_warmonger_mage_attack.ogg",
			"kr4_warmonger_mage_healingroots.ogg",
			"kr4_warmonger_mage_meteorshower_impact.ogg",
			"kr4_warmonger_mage_meteorshower_preimpact.ogg",
			"kr4_warmonger_mage_electroshock_upg.ogg",
			"kr4_warmonger_mage_healing_roots_upg.ogg",
			"kr4_warmonger_mage_meteorites_upg.ogg",
			"kr4_warmonger_mage_taunt_4.ogg",
			"kr4_warmonger_mage_taunt_1.ogg",
			"kr4_warmonger_mage_taunt_2.ogg",
			"kr4_warmonger_mage_taunt_3.ogg",
        },
    },
    tower_rocket_riders = {
        files = {
            "kr4_warmonger_rocket_attack_missile.ogg",
			"kr4_warmonger_rocket_fail_engine.ogg",
			"kr4_warmonger_rocket_failed_engines_upg.ogg",
			"kr4_warmonger_rocket_minefield.ogg",
			"kr4_warmonger_rocket_minefield_upg.ogg",
			"kr4_warmonger_rocket_nitroboosters.ogg",
			"kr4_warmonger_rocket_nitro_boosters_upg.ogg",
			"kr4_warmonger_rocket_taunt_4.ogg",
			"kr4_warmonger_rocket_taunt_1.ogg",
			"kr4_warmonger_rocket_taunt_2.ogg",
			"kr4_warmonger_rocket_taunt_3.ogg",
        },
    },
    tower_grim_cemetery = {
        files = {
			"kr4_fallen_ones_grim_cemetery_taunt_4.ogg",
			"kr4_fallen_ones_grim_cemetery_taunt_1.ogg",
			"kr4_fallen_ones_grim_cemetery_taunt_2.ogg",
			"kr4_fallen_ones_grim_cemetery_taunt_3.ogg",
			"kr4_fallen_ones_grim_cemetery_cold_grip_upg.ogg",
			"kr4_fallen_ones_grim_cemetery_better_zombies_upg.ogg",
			"kr4_fallen_ones_grim_cemetery_summon_moan2.ogg",
			"kr4_fallen_ones_grim_cemetery_summon_moan3.ogg",
			"kr4_fallen_ones_grim_cemetery_summon_moan4.ogg",
			"kr4_fallen_ones_grim_cemetery_summon_gravel.ogg",
			"kr4_fallen_ones_grim_cemetery_coldgrip.ogg",
			"kr4_fallen_ones_grim_cemetery_bloatedcorpses.ogg",
            "kr4_ember_lords_mage_overcharge.ogg",
            "kr4_fallen_ones_grim_cemetery_bloated_zombies_upg.ogg"
        }
    },
    tower_deep_devils = {
        files = {
            "kr4_deep_devils_amph_upg.ogg",
            "kr4_deep_devils_net_upg.ogg",
            "kr4_deep_devils_storm_upg.ogg",
            "kr4_deep_devils_taunt_1.ogg",
            "kr4_deep_devils_taunt_2.ogg",
            "kr4_deep_devils_taunt_3.ogg",
            "kr4_deep_devils_taunt_4.ogg",
            "kr4_deep_devils_towertrap_catch.ogg",
            "kr4_deep_devils_towertrap_throw.ogg",
        }
    },
    tower_sandworm = {
        files = {
            "kr4_sfx_tower_tremor_voice_towerConstruction_v1.ogg",
            "kr4_sfx_tower_tremor_voice_towerUpgrade_v1.ogg",
            "kr4_sfx_tower_tremor_voice_towerSkill_v1.ogg",
            
            "kr4_sfx_tower_tremor_attack_v1.ogg",
            "kr4_sfx_tower_tremor_instakill_bite_v1.ogg",
            "kr4_sfx_tower_tremor_instakill_in_v1.ogg",
            "kr4_sfx_tower_tremor_instakill_out_v1.ogg",
            "kr4_sfx_tower_tremor_spawn_var1_v1.ogg",
            "kr4_sfx_tower_tremor_spawn_var2_v1.ogg",
            "kr4_sfx_tower_tremor_spawn_var3_v1.ogg",
            "kr4_sfx_tower_tremor_spit_splat_v1.ogg",
            "kr4_sfx_tower_tremor_spit_v1.ogg",
        }
    },
    hero_eiskalt = {
		files = {
        "kr4_hero_eiskalt_taunt_1.ogg",
        "kr4_hero_eiskalt_taunt_2.ogg",
        "kr4_hero_eiskalt_taunt_3.ogg",
        "kr4_hero_eiskalt_taunt_4.ogg",
        "kr4_hero_eiskalt_taunt_death.ogg",
        "kr4_hero_jigou_breath.ogg",
        "kr4_hero_eiskalt_frosty_explodes.ogg",
        "kr4_hero_eiskalt_frosty_roll_loop.ogg",
        "kr4_hero_eiskalt_frosty_impact_loopstart.ogg",
        "kr4_hero_eiskalt_frosty_throw.ogg",
        "kr4_hero_eiskalt_icepeaks.ogg",
        "kr4_hero_beresad_attack_shot.ogg",
		}
	},
    hero_jack_o_lantern = {
        files = {
			"kr4_hero_jacko_taunt_1.ogg",
			"kr4_hero_jacko_taunt_2.ogg",
			"kr4_hero_jacko_taunt_3.ogg",
			"kr4_hero_jacko_taunt_4.ogg",
			"kr4_hero_jacko_teleport_var1.ogg",
			"kr4_hero_jacko_teleport_var2.ogg",
			"kr4_hero_jacko_taunt_death.ogg",
			"kr4_hero_jacko_teleport_var1.ogg",
			"kr4_hero_jacko_teleport_var2.ogg",
			"kr4_hero_jacko_horses.ogg",
        }
    },
    hero_murglun = {
        files = {
            "kr4_hero_murglun_taunt_1.ogg",
			"kr4_hero_murglun_taunt_2.ogg",
			"kr4_hero_murglun_taunt_3.ogg",
			"kr4_hero_murglun_taunt_4.ogg",
			"kr4_hero_murglun_taunt_death.ogg",
			"kr4_hero_murglun_infernalheat_whirlwind_loop.ogg",
			"kr4_hero_murglun_infernalheat_whirlwind_loopstart.ogg",
        },
    },
    hero_beresad = {
        files = {
            "kr4_hero_beresad_attack_impact.ogg",
            "kr4_hero_beresad_attack_shot.ogg",
            "kr4_hero_beresad_conflagration.ogg",
            "kr4_hero_beresad_fear.ogg",
            "kr4_hero_beresad_flames_loop.ogg",
            "kr4_hero_beresad_flames_loopend.ogg",
            "kr4_hero_beresad_flames_loopstart.ogg",
            "kr4_hero_beresad_hellfire_firerain.ogg",
            "kr4_hero_beresad_remove.ogg",
            "kr4_hero_beresad_spawn_impact.ogg",
            "kr4_hero_beresad_spawn_spit.ogg",
            "kr4_hero_beresad_taunt_1.ogg",
            "kr4_hero_beresad_taunt_2.ogg",
            "kr4_hero_beresad_taunt_3.ogg",
            "kr4_hero_beresad_taunt_4.ogg",
            "kr4_hero_beresad_taunt_death.ogg",
        }
    },      
    hero_lucerna = {
        files = {
            "kr_voice_lucerna_death_b.ogg",
            "kr_voice_lucerna_select01_a.ogg",
            "kr_voice_lucerna_select02_c.ogg",
            "kr_voice_lucerna_select03_d.ogg",
            "kr_voice_lucerna_select04_a.ogg",
            "krv_sfx_hero_lucerna_attack_var1_v1.ogg",
            "krv_sfx_hero_lucerna_attack_var2_v1.ogg",
            "krv_sfx_hero_lucerna_attack_var3_v1.ogg",
            "krv_sfx_hero_lucerna_ghost_summon_op1_v1.ogg",
            "krv_sfx_hero_lucerna_ghost_summon_op2_v1.ogg",
            "krv_sfx_hero_lucerna_ghost_summon_op3_v1.ogg",
            "krv_sfx_hero_lucerna_ghost_summon_op4_v1.ogg",
            "krv_sfx_hero_lucerna_respawn_v1.ogg",
            "krv_sfx_hero_lucerna_scare_op1_v1.ogg",
            "krv_sfx_hero_lucerna_scare_op2_v1.ogg",
            "krv_sfx_hero_lucerna_teleport_v1.ogg",
            "krv_sfx_hero_lucerna_ultimate_flag_ghostCast_var1_v1.ogg",
            "krv_sfx_hero_lucerna_ultimate_flag_ghostCast_var2_v1.ogg",
            "krv_sfx_hero_lucerna_ultimate_flag_ghostCast_var3_v1.ogg",
            "krv_sfx_hero_lucerna_ultimate_flag_totem-In_v1.ogg",
            "krv_sfx_hero_lucerna_ultimate_flag_totem-Out_1.ogg",
            "kr4_fallen_ones_spirit_mausoleum_possession_hit.ogg",
        }
    },
    hero_tank = {
        files = {
            "kr4_hero_tank_airstrike_bomb.ogg",
            "kr4_hero_tank_airstrike_flames.ogg",
            "kr4_hero_tank_groundslam_impact.ogg",
            "kr4_hero_tank_groundslam_lift.ogg",
            "kr4_hero_tank_scorching_loop.ogg",
            "kr4_hero_tank_scorching_loopend.ogg",
            "kr4_hero_tank_scorching_loopstart.ogg",
            "kr4_hero_tank_taunt_1.ogg",
            "kr4_hero_tank_taunt_2.ogg",
            "kr4_hero_tank_taunt_3.ogg",
            "kr4_hero_tank_taunt_4.ogg",
            "kr4_hero_tank_taunt_death.ogg",
            "kra_sfx_heroes_onagro_deathFromAbove_attack_shot_var1_v1.ogg",
			"kra_sfx_heroes_onagro_deathFromAbove_attack_shot_var2_v1.ogg",
			"kra_sfx_heroes_onagro_deathFromAbove_attack_shot_var3_v1.ogg",
        }
    },
    hero_asra = {
        files = {
			"kr4_hero_asra_taunt_1.ogg",
			"kr4_hero_asra_taunt_2.ogg",
			"kr4_hero_asra_taunt_3.ogg",
			"kr4_hero_asra_taunt_4.ogg",
			"kr4_hero_asra_taunt_death.ogg",
			"kr4_hero_asra_shadowdance_teleport.ogg",
			"kr4_hero_asra_shield.ogg",
			"kr4_hero_asra_spiderbite_attack.ogg",
			"kr4_hero_asra_toxicrain_impactwithpoison.ogg",
        }
    },
    hero_orc = {
        files = {
            "kr4_hero_orc_taunt_1.ogg",
            "kr4_hero_orc_taunt_2.ogg",
            "kr4_hero_orc_taunt_3.ogg",
            "kr4_hero_orc_taunt_4.ogg",
            "kr4_hero_orc_taunt_death.ogg",
            "kr4_hero_veruk_aimedslashes.ogg",
            "kr4_hero_veruk_bruteforce.ogg",
            "kr4_hero_veruk_enterwarmongers.ogg",
            "kr4_hero_veruk_inspiringleader.ogg",
        }
    },
    hero_oloch = {
        files = {
            "kr4_hero_oloch_demonicblast_cast.ogg",
            "kr4_hero_oloch_demonicblast_travel.ogg",
            "kr4_hero_oloch_duplication.ogg",
            "kr4_hero_oloch_hellishpact.ogg",
            "kr4_hero_oloch_magmaeruption.ogg",
            "kr4_hero_oloch_sealisolation.ogg",
            "kr4_hero_oloch_taunt_1.ogg",
            "kr4_hero_oloch_taunt_2.ogg",
            "kr4_hero_oloch_taunt_3.ogg",
            "kr4_hero_oloch_taunt_4.ogg",
            "kr4_hero_oloch_taunt_death.ogg",
            "kr4_ember_lords_mage_attack.ogg",
        }
    },
    sounds_stage150 = {
		sounds = {
			"MusicBattlePrep_150",
			"MusicBattle_150",
		}
	},
    sounds_stage151 = {
		sounds = {
			"MusicBattlePrep_151",
			"MusicBattle_151",
		}
	},
    sounds_stage152 = {
		sounds = {
			"MusicBattlePrep_152",
			"MusicBattle_152",
		}
	},
    sounds_stage176 = {
		sounds = {
			"MusicBattlePrep_176",
			"MusicBattle_176",
			"dark_army_blazing_mage_attack_loopstart",
            "puff_death_sound",
            "haunted_skeleton_death",
            "haunted_skeleton_death",
            "ElvesCreepScreecherDeath",
            "dwarves_sulfur_alchemist_death",
            "corrosive_soul_death",
		}
	},
	sounds_stage177 = {
		sounds = {
			"MusicBattlePrep_177",
			"MusicBattle_177",
			"level27_gillman_jump",
			"level27_gillman_appear",
			"level27_girl_drinking",
			"dark_army_blazing_mage_attack_loopstart",
            "puff_death_sound",
            "haunted_skeleton_death",
            "ElvesCreepScreecherDeath",
            "dwarves_sulfur_alchemist_death",
            "corrosive_soul_death",
		}
	},
    sounds_stage426 = {
		sounds = {
			"MusicBattlePrep_71",
			"MusicBattle_71",
			"dark_army_blazing_mage_attack_loopstart",
            "puff_death_sound",
            "haunted_skeleton_death",
            "haunted_skeleton_death",
            "ElvesCreepScreecherDeath",
            "dwarves_sulfur_alchemist_death",
            "corrosive_soul_death",
		}
	},
	sounds_stage427 = {
		sounds = {
			"MusicBattlePrep_72",
			"MusicBattle_72",
			"level27_gillman_jump",
			"level27_gillman_appear",
			"level27_girl_drinking",
			"dark_army_blazing_mage_attack_loopstart",
            "puff_death_sound",
            "haunted_skeleton_death",
            "ElvesCreepScreecherDeath",
            "dwarves_sulfur_alchemist_death",
            "corrosive_soul_death",
		}
	},
    sounds_stage176 = {
		sounds = {
			"MusicBattlePrep_176",
			"MusicBattle_176",
			"dark_army_blazing_mage_attack_loopstart",
            "puff_death_sound",
            "haunted_skeleton_death",
            "haunted_skeleton_death",
            "ElvesCreepScreecherDeath",
            "dwarves_sulfur_alchemist_death",
            "corrosive_soul_death",
		}
	},
	sounds_stage177 = {
		sounds = {
			"MusicBattlePrep_177",
			"MusicBattle_177",
			"level27_gillman_jump",
			"level27_gillman_appear",
			"level27_girl_drinking",
			"dark_army_blazing_mage_attack_loopstart",
            "puff_death_sound",
            "haunted_skeleton_death",
            "ElvesCreepScreecherDeath",
            "dwarves_sulfur_alchemist_death",
            "corrosive_soul_death",
		}
	},
	common = {
		keep = true,
		files = {
			"legionnaire_taunt_1.ogg",
			"legionnaire_taunt_2.ogg",
			"kre_sfx_arivan_fireballsummon[op2].ogg"
		},
		ids = {},
	},
}