-- chunkname: @./_assets/kr1-desktop/strings/zh-Hans.lua

return {
	HERO_SPIDER_CLASS = "万毒蛛后",
	HERO_VESPER_ATTACKRATE = "快",
	--HERO_VELANN_ATTACKRATE = "",
	HERO_SPACE_ELF_ATTACKRATE = "平均",
	HERO_MUYRN_ATTACKRATE = "平均",
	HERO_LUMENIR_ATTACKRATE = "慢",
	HERO_RAELYN_ATTACKRATE = "慢",
	HERO_BUILDER_ATTACKRATE = "慢",
	HERO_MECHA_ATTACKRATE = "慢",
	HERO_VENOM_ATTACKRATE = "快",
	HERO_ROBOT_ATTACKRATE = "快",
	HERO_HUNTER_ATTACKRATE = "快",
	HERO_DRAGON_GEM_ATTACKRATE = "慢",
	HERO_BIRD_ATTACKRATE = "平均",
	HERO_LAVA_ATTACKRATE = "平均",
	HERO_WITCH_ATTACKRATE = "平均",
	HERO_DRAGON_ARB_ATTACKRATE = "慢",
	HERO_DRAGON_BONE_ATTACKRATE = "慢",
	HERO_SPIDER_ATTACKRATE = "平均",
}
